const baseDeDonnees = [
    {"nom": "'N SYNC", "info": "", "prochains": [], "majeurs": []},
    {"nom": "24KGOLDN", "info": "", "prochains": [], "majeurs": []},
    {"nom": "2FRERES", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ADELE", "info": "", "prochains": [], "majeurs": []},
    {"nom": "AGUILERA/L.KIM/MYA/PINK", "info": "", "prochains": [], "majeurs": []},
    {"nom": "AKON", "info": "", "prochains": [], "majeurs": [{"date": "26 juin", "salle": "Centre Bell (avec Ne-Yo)"}]},
    {"nom": "ALEX NEVSKY", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ALEX WARREN", "info": "", "prochains": [], "majeurs": [{"date": "8 juillet 19h30", "salle": "Centre Bell"}]},
    {"nom": "ALEXE", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ALFA ROCOCO", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ALICIA KEYS", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ALICIA MOFFET", "info": "", "prochains": [{"date": "15 août", "salle": "Montgolfières St-Jean"}], "majeurs": []},
    {"nom": "ALIOCHA SCHNEIDER", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ALLIANCE ETHNIK", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ANASTACIA", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ANDEE", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ANDREANNE A. MALETTE", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ANGELE", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ANJXLXE", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ARIANA GRANDE", "info": "", "prochains": [], "majeurs": [{"date": "30 et 31 juillet 20h", "salle": "Centre Bell"}]},
    {"nom": "ARIANE BRUNET", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ARIANE MOFFATT", "info": "", "prochains": [], "majeurs": []},
    {"nom": "ASWELL", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BACKSTREET BOYS", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BAD BUNNY", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BBNO$", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BEN L'ONCLE SOUL", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BENSON BOONE", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BEYONCE", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BIGFLO & OLI", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BILLIE EILISH", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BLACK EYED PEAS", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BLACK EYED PEAS/OZUNA/J.REY", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BLEU JEANS BLEU", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BLU CANTRELL", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BOB MARLEY & THE WAILERS", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BOB SINCLAR & KIESZA", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BON JOVI", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BRANDY W/MONICA", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BRITNEY SPEARS", "info": "", "prochains": [], "majeurs": []},
    {"nom": "BRUNO MARS", "info": "Denis Fortin a offert les billets de Bruno Mars à Violaine Lancteau (TEST)", "prochains": [], "majeurs": [{"date": "23 au 30 Mai 2026", "salle": "Rogers Stadium, Toronto"}]},
    {"nom": "BRYAN ADAMS", "info": "", "prochains": [], "majeurs": [{"date": "24 aout 20h", "salle": "Amphithéâtre Cogeco-Trois Rivières"}]},
    {"nom": "CALUM SCOTT", "info": "", "prochains": [{"date": "26 avril 20h", "salle": "MTelus"}], "majeurs": []},
    {"nom": "CALVIN HARRIS", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CAMILA CABELLO", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CARLY RAE JEPSEN", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CELINE DION", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CHAPPELL ROAN", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CHARLIE PUTH", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CHARLIE-ROSE", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CHARLOTTE CARDIN", "info": "", "prochains": [{"date": "23 Avril 2026", "salle": "Rennes, France"}, {"date": "24 Avril 2026", "salle": "Arkéa Arena, Floirac"}, {"date": "15 juillet", "salle": "Fête du Lac des Nations"}], "majeurs": []},
    {"nom": "CHRISTINA AGUILERA", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CLASSE MOYENNE", "info": "", "prochains": [{"date": "2 avril 20h", "salle": "Club Dix 30"}], "majeurs": []},
    {"nom": "CLASSE MOYENNE & RYMZ", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CLAUDE BEGIN", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CLAY AND FRIENDS", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CLEAN BANDIT & ANNE-MARIE", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CLEMENT JACQUES", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CLODELLE", "info": "", "prochains": [], "majeurs": []},
    {"nom": "COEUR DE PIRATE", "info": "", "prochains": [], "majeurs": []},
    {"nom": "COLBIE CAILLAT", "info": "", "prochains": [], "majeurs": []},
    {"nom": "COLDPLAY", "info": "", "prochains": [], "majeurs": []},
    {"nom": "COMMENT DEBORD", "info": "", "prochains": [], "majeurs": []},
    {"nom": "COOLIO", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CORNEILLE", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CRIS CAB", "info": "", "prochains": [], "majeurs": []},
    {"nom": "CYRIL", "info": "", "prochains": [], "majeurs": []},
    {"nom": "D GUETTA, T SWIMS, TONES AND I", "info": "", "prochains": [], "majeurs": []},
    {"nom": "DAFT PUNK", "info": "", "prochains": [], "majeurs": []},
    {"nom": "DAMIEN LAURETTA", "info": "", "prochains": [], "majeurs": []},
    {"nom": "DANIEL BELANGER", "info": "", "prochains": [], "majeurs": []},
    {"nom": "DASHA", "info": "", "prochains": [], "majeurs": []},
    {"nom": "DAVID GUETTA", "info": "", "prochains": [], "majeurs": []},
    {"nom": "DESTINY'S CHILD", "info": "", "prochains": [], "majeurs": []},
    {"nom": "DIDO", "info": "", "prochains": [], "majeurs": []},
    {"nom": "DOBACARACOL", "info": "", "prochains": [], "majeurs": []},
    {"nom": "DOMENO", "info": "", "prochains
