const baseArtistes = [
    {"nom": "112", "prochains": [], "majeurs": []},
    {"nom": "1975", "prochains": [], "majeurs": []},
    {"nom": "2 BROTHERS ON THE 4TH FLOOR", "prochains": [], "majeurs": []},
    {"nom": "2 BE 3", "prochains": [], "majeurs": []},
    {"nom": "21 SAVAGE", "prochains": [], "majeurs": []},
    {"nom": "24KGOLDN", "prochains": [], "majeurs": []},
    {"nom": "2PAC", "prochains": [], "majeurs": []},
    {"nom": "4 THE CAUSE", "prochains": [], "majeurs": []},
    {"nom": "50 CENT", "prochains": [], "majeurs": []},
    {"nom": "5 SECONDS OF SUMMER", "prochains": [], "majeurs": []},
    {"nom": "A FLOCK OF SEAGULLS", "prochains": [], "majeurs": []},
    {"nom": "A GREAT BIG WORLD", "prochains": [], "majeurs": []},
    {"nom": "A.B. QUINTANILLA Y LOS KUMBI", "prochains": [], "majeurs": []},
    {"nom": "AAROH", "prochains": [], "majeurs": []},
    {"nom": "ABBA", "prochains": [], "majeurs": []},
    {"nom": "AC/DC", "prochains": [], "majeurs": []},
    {"nom": "ACE OF BASE", "prochains": [], "majeurs": []},
    {"nom": "ADAM LAMBERT", "prochains": [], "majeurs": []},
    {"nom": "ADAM LEVINE", "prochains": [], "majeurs": []},
    {"nom": "ADELE", "prochains": [], "majeurs": []},
    {"nom": "AFROJACK", "prochains": [], "majeurs": []},
    {"nom": "AFROMAN", "prochains": [], "majeurs": []},
    {"nom": "AGNEZ MO", "prochains": [], "majeurs": []},
    {"nom": "A-HA", "prochains": [], "majeurs": []},
    {"nom": "AKON", "prochains": [], "majeurs": [{"date": "26 juin", "salle": "Centre Bell (avec Ne-Yo)"}]},
    {"nom": "ALAN JACKSON", "prochains": [], "majeurs": []},
    {"nom": "ALAN WALKER", "prochains": [], "majeurs": []},
    {"nom": "ALANIS MORISSETTE", "prochains": [], "majeurs": []},
    {"nom": "ALANNAH MYLES", "prochains": [], "majeurs": []},
    {"nom": "ALCORN", "prochains": [], "majeurs": []},
    {"nom": "ALESSIA CARA", "prochains": [], "majeurs": []},
    {"nom": "ALESSO", "prochains": [], "majeurs": []},
    {"nom": "ALEX NEVSKY", "prochains": [], "majeurs": []},
    {"nom": "ALEX WARREN", "prochains": [], "majeurs": [{"date": "8 juillet 19h30", "salle": "Centre Bell"}]},
    {"nom": "ALEXIA", "prochains": [], "majeurs": []},
    {"nom": "ALI GATIE", "prochains": [], "majeurs": []},
    {"nom": "ALICE DEEJAY", "prochains": [], "majeurs": []},
    {"nom": "ALICE MERTON", "prochains": [], "majeurs": []},
    {"nom": "ALICIA KEYS", "prochains": [], "majeurs": []},
    {"nom": "ALICIA MOFFET", "prochains": [{"date": "15 août", "salle": "Montgolfières St-Jean"}], "majeurs": []},
    {"nom": "ALISON KRAUSS", "prochains": [], "majeurs": []},
    {"nom": "ALL 4 ONE", "prochains": [], "majeurs": []},
    {"nom": "ALL SAINTS", "prochains": [], "majeurs": []},
    {"nom": "ALL-AMERICAN REJECTS", "prochains": [], "majeurs": []},
    {"nom": "ALLIANCE ETHNIK", "prochains": [], "majeurs": []},
    {"nom": "ALOE BLACC", "prochains": [], "majeurs": []},
    {"nom": "ALOK", "prochains": [], "majeurs": []},
    {"nom": "ALPHAVILLE", "prochains": [], "majeurs": []},
    {"nom": "AMY WINEHOUSE", "prochains": [], "majeurs": []},
    {"nom": "ANDREA BOCELLI", "prochains": [], "majeurs": []},
    {"nom": "ANDREW WYATT", "prochains": [], "majeurs": []},
    {"nom": "ANDY GRAMMER", "prochains": [], "majeurs": []},
    {"nom": "ANITA BAKER", "prochains": [], "majeurs": []},
    {"nom": "ANITA WARD", "prochains": [], "majeurs": []},
    {"nom": "ANNE-MARIE", "prochains": [], "majeurs": []},
    {"nom": "ANNIE LENOX", "prochains": [], "majeurs": []},
    {"nom": "AQUA", "prochains": [], "majeurs": []},
    {"nom": "ARCTIC MONKEYS", "prochains": [], "majeurs": []},
    {"nom": "ARETHA FRANKLIN", "prochains": [], "majeurs": []},
    {"nom": "ARIANA GRANDE", "prochains": [], "majeurs": [{"date": "30 et 31 juillet 20h", "salle": "Centre Bell"}]},
    {"nom": "ARMIN VAN BUUREN", "prochains": [], "majeurs": []},
    {"nom": "A-TEENS", "prochains": [], "majeurs": []},
    {"nom": "ATB", "prochains": [], "majeurs": []},
    {"nom": "ATOMIC KITTEN", "prochains": [], "majeurs": []},
    {"nom": "AUDIOSLAVE", "prochains": [], "majeurs": []},
    {"nom": "AURORA", "prochains": [], "majeurs": []},
    {"nom": "AVA MAX", "prochains": [], "majeurs": []},
    {"nom": "AVANT", "prochains": [], "majeurs": []},
    {"nom": "AVICII", "prochains": [], "majeurs": []},
    {"nom": "AVRIL LAVIGNE", "prochains": [], "majeurs": []},
    {"nom": "AWOLNATION", "prochains": [], "majeurs": []},
    {"nom": "AXWELL", "prochains": [], "majeurs": []},
    {"nom": "AYLKS", "prochains": [], "majeurs": []},
    {"nom": "B-52'S", "prochains": [], "majeurs": []},
    {"nom": "BABYFACE", "prochains": [], "majeurs": []},
    {"nom": "BACKSTREET BOYS", "prochains": [], "majeurs": []},
    {"nom": "BAD BUNNY", "prochains": [], "majeurs": []},
    {"nom": "BAD ENGLISH", "prochains": [], "majeurs": []},
    {"nom": "BALTIMORA", "prochains": [], "majeurs": []},
    {"nom": "BAMBOU", "prochains": [], "majeurs": []},
    {"nom": "BANANARAMA", "prochains": [], "majeurs": []},
    {"nom": "BAND AID", "prochains": [], "majeurs": []},
    {"nom": "BANNERS", "prochains": [], "majeurs": []},
    {"nom": "BARBRA STREISAND", "prochains": [], "majeurs": []},
    {"nom": "BARENAKED LADIES", "prochains": [], "majeurs": []},
    {"nom": "BASEMENT JAXX", "prochains": [], "majeurs": []},
    {"nom": "BASTILLE", "prochains": [], "majeurs": []},
    {"nom": "BEASTIE BOYS", "prochains": [], "majeurs": []},
    {"nom": "BEATLES", "prochains": [], "majeurs": []},
    {"nom": "BECK", "prochains": [], "majeurs": []},
    {"nom": "BECKY G", "prochains": [], "majeurs": []},
    {"nom": "BEE GEES", "prochains": [], "majeurs": []},
    {"nom": "BELINDA CARLISLE", "prochains": [], "majeurs": []},
    {"nom": "BELL BIV DEVOE", "prochains": [], "majeurs": []},
    {"nom": "BELLE PEREZ", "prochains": [], "majeurs": []},
    {"nom": "BEN E. KING", "prochains": [], "majeurs": []},
    {"nom": "BEN HARPER", "prochains": [], "majeurs": []},
    {"nom": "BENNY BENASSI", "prochains": [], "majeurs": []},
    {"nom": "BENNY BLANCO", "prochains": [], "majeurs": []},
    {"nom": "BENNY MARDONES", "prochains": [], "majeurs": []},
    {"nom": "BERLIN", "prochains": [], "majeurs": []},
    {"nom": "BEYONCE", "prochains": [], "majeurs": []},
    {"nom": "BIG MOUNTAIN", "prochains": [], "majeurs": []},
    {"nom": "BILL MEDLEY", "prochains": [], "majeurs": []},
    {"nom": "BILLIE EILISH", "prochains": [], "majeurs": []},
    {"nom": "BILLIE MYERS", "prochains": [], "majeurs": []},
    {"nom": "BILLY CURRINGTON", "prochains": [], "majeurs": []},
    {"nom": "BILLY IDOL", "prochains": [], "majeurs": []},
    {"nom": "BILLY JOEL", "prochains": [], "majeurs": []},
    {"nom": "BILLY OCEAN", "prochains": [], "majeurs": []},
    {"nom": "BING CROSBY", "prochains": [], "majeurs": []},
    {"nom": "BJORK", "prochains": [], "majeurs": []},
    {"nom": "BLACK BOX", "prochains": [], "majeurs": []},
    {"nom": "BLACK EYED PEAS", "prochains": [], "majeurs": []},
    {"nom": "BLACK KEYS", "prochains": [], "majeurs": []},
    {"nom": "BLACK MACHINE", "prochains": [], "majeurs": []},
    {"nom": "BLACKSTREET", "prochains": [], "majeurs": []},
    {"nom": "BLANCO BROWN", "prochains": [], "majeurs": []},
    {"nom": "BLESSID UNION OF SOULS", "prochains": [], "majeurs": []},
    {"nom": "BLIND MELON", "prochains": [], "majeurs": []},
    {"nom": "BLINK 182", "prochains": [], "majeurs": []},
    {"nom": "BLONDIE", "prochains": [], "majeurs": []},
    {"nom": "BLOODHOUND GANG", "prochains": [], "majeurs": []},
    {"nom": "BLUE", "prochains": [], "majeurs": []},
    {"nom": "BLUE OYSTER CULT", "prochains": [], "majeurs": []},
    {"nom": "BLUE SWEDE", "prochains": [], "majeurs": []},
    {"nom": "BLUR", "prochains": [], "majeurs": []},
    {"nom": "BOB DYLAN", "prochains": [], "majeurs": []},
    {"nom": "BOB MARLEY", "prochains": [], "majeurs": []},
    {"nom": "BOB SINCLAR", "prochains": [], "majeurs": []},
    {"nom": "BOBBY BROWN", "prochains": [], "majeurs": []},
    {"nom": "BOBBY MCFERRIN", "prochains": [], "majeurs": []},
    {"nom": "BOMB THE BASS", "prochains": [], "majeurs": []},
    {"nom": "BON JOVI", "prochains": [], "majeurs": []},
    {"nom": "BONEY M", "prochains": [], "majeurs": []},
    {"nom": "BONNIE TYLER", "prochains": [], "majeurs": []},
    {"nom": "BOSTON", "prochains": [], "majeurs": []},
    {"nom": "BOUCHERVILLE", "prochains": [], "majeurs": []},
    {"nom": "BOW WOW WOW", "prochains": [], "majeurs": []},
    {"nom": "BOY GEORGE", "prochains": [], "majeurs": []},
    {"nom": "BOYS LIKE GIRLS", "prochains": [], "majeurs": []},
    {"nom": "BOYS TOWN GANG", "prochains": [], "majeurs": []},
    {"nom": "BOYZ II MEN", "prochains": [], "majeurs": []},
    {"nom": "BRAD PAISLEY", "prochains": [], "majeurs": []},
    {"nom": "BRANDY", "prochains": [], "majeurs": []},
    {"nom": "BRIAN MCKNIGHT", "prochains": [], "majeurs": []},
    {"nom": "BRITNEY SPEARS", "prochains": [], "majeurs": []},
    {"nom": "BRONSKI BEAT", "prochains": [], "majeurs": []},
    {"nom": "BRUCE HORNSBY", "prochains": [], "majeurs": []},
    {"nom": "BRUCE SPRINGSTEEN", "prochains": [], "majeurs": []},
    {"nom": "BRUNO MARS", "info": "Denis Fortin a offert les billets de Bruno Mars à Violaine Lancteau (TEST)", "prochains": [], "majeurs": []},
    {"nom": "BRYAN ADAMS", "prochains": [], "majeurs": [{"date": "24 aout 20h", "salle": "Amphithéâtre Cogeco-Trois Rivières"}]},
    {"nom": "BUSTA RHYMES", "prochains": [], "majeurs": []},
    {"nom": "C&C MUSIC FACTORY", "prochains": [], "majeurs": []},
    {"nom": "CALUM SCOTT", "prochains": [], "majeurs": [{"date": "26 avril 20h", "salle": "MTelus"}]},
    {"nom": "CALVIN HARRIS", "prochains": [], "majeurs": []},
    {"nom": "CAMEO", "prochains": [], "majeurs": []},
    {"nom": "CAMILA CABELLO", "prochains": [], "majeurs": []},
    {"nom": "CAPITAL CITIES", "prochains": [], "majeurs": []},
    {"nom": "CARDI B", "prochains": [], "majeurs": []},
    {"nom": "CARL DOUGLAS", "prochains": [], "majeurs": []},
    {"nom": "CARLY RAE JEPSEN", "prochains": [], "majeurs": []},
    {"nom": "CARNIVAL IN COAL", "prochains": [], "majeurs": []},
    {"nom": "CARRIE UNDERWOOD", "prochains": [], "majeurs": []},
    {"nom": "CASCADA", "prochains": [], "majeurs": []},
    {"nom": "CECE PENISTON", "prochains": [], "majeurs": []},
    {"nom": "CELINE DION", "prochains": [], "majeurs": []},
    {"nom": "CHAKA DEMUS & PLIERS", "prochains": [], "majeurs": []},
    {"nom": "CHAKA KHAN", "prochains": [], "majeurs": []},
    {"nom": "CHARLIE PUTH", "prochains": [], "majeurs": []},
    {"nom": "CHARLOTTE CARDIN", "prochains": [{"date": "15 juillet", "salle": "Fête du Lac des Nations"}], "majeurs": []},
    {"nom": "CHEAP TRICK", "prochains": [], "majeurs": []},
    {"nom": "CHER", "prochains": [], "majeurs": []},
    {"nom": "CHIC", "prochains": [], "majeurs": []},
    {"nom": "CHICAGO", "prochains": [], "majeurs": []},
    {"nom": "CHRIS BROWN", "prochains": [], "majeurs": []},
    {"nom": "CHRIS CORNELL", "prochains": [], "majeurs": []},
    {"nom": "CHRIS ISAAK", "prochains": [], "majeurs": []},
    {"nom": "CHRISTINA AGUILERA", "prochains": [], "majeurs": []},
    {"nom": "CHRISTINA PERRI", "prochains": [], "majeurs": []},
    {"nom": "CHRISTOPHER CROSS", "prochains": [], "majeurs": []},
    {"nom": "CHUBBY CHECKER", "prochains": [], "majeurs": []},
    {"nom": "CHUMBAWAMBA", "prochains": [], "majeurs": []},
    {"nom": "CIARA", "prochains": [], "majeurs": []},
    {"nom": "CLASSE MOYENNE", "prochains": [{"date": "2 avril 20h", "salle": "Club Dix 30"}], "majeurs": []},
    {"nom": "CLEAN BANDIT", "prochains": [], "majeurs": []},
    {"nom": "CLINTON KANE", "prochains": [], "majeurs": []},
    {"nom": "COBRA STARSHIP", "prochains": [], "majeurs": []},
    {"nom": "COCOLOMES", "prochains": [], "majeurs": []},
    {"nom": "COLDPLAY", "prochains": [], "majeurs": []},
    {"nom": "COLLECTIVE SOUL", "prochains": [], "majeurs": []},
    {"nom": "COLOR ME BADD", "prochains": [], "majeurs": []},
    {"nom": "CONAN GRAY", "prochains": [], "majeurs": []},
    {"nom": "COOLIO", "prochains": [], "majeurs": []},
    {"nom": "CORONA", "prochains": [], "majeurs": []},
    {"nom": "COUNTING CROWS", "prochains": [], "majeurs": []},
    {"nom": "CRAIG DAVID", "prochains": [], "majeurs": []},
    {"nom": "CRANBERRIES", "prochains": [], "majeurs": []},
    {"nom": "CRAZY TOWN", "prochains": [], "majeurs": []},
    {"nom": "CREED", "prochains": [], "majeurs": []},
    {"nom": "CREEDENCE CLEARWATER REVIVAL", "prochains": [], "majeurs": []},
    {"nom": "CROWDED HOUSE", "prochains": [], "majeurs": []},
    {"nom": "CRYSTAL WATERS", "prochains": [], "majeurs": []},
    {"nom": "CULTURE BEAT", "prochains": [], "majeurs": []},
    {"nom": "CULTURE CLUB", "prochains": [], "majeurs": []},
    {"nom": "CUTTING CREW", "prochains": [], "majeurs": []},
    {"nom": "CYNDI LAUPER", "prochains": [], "majeurs": []},
    {"nom": "CYPRESS HILL", "prochains": [], "majeurs": []},
    {"nom": "DADDY YANKEE", "prochains": [], "majeurs": []},
    {"nom": "DAFT PUNK", "prochains": [], "majeurs": []},
    {"nom": "DAN+SHAY", "prochains": [], "majeurs": []},
    {"nom": "DANIEL BEDINGFIELD", "prochains": [], "majeurs": []},
    {"nom": "DANIEL POWTER", "prochains": [], "majeurs": []},
    {"nom": "DANNY GOKEY", "prochains": [], "majeurs": []},
    {"nom": "DARIUS RUCKER", "prochains": [], "majeurs": []},
    {"nom": "DARYL HALL", "prochains": [], "majeurs": []},
    {"nom": "DASHBOARD CONFESSIONAL", "prochains": [], "majeurs": []},
    {"nom": "DAVID BOWIE", "prochains": [], "majeurs": []},
    {"nom": "DAVID CRAIG", "prochains": [], "majeurs": []},
    {"nom": "DAVID GUETTA", "prochains": [], "majeurs": []},
    {"nom": "DAVID KUSHNER", "prochains": [], "majeurs": []},
    {"nom": "DAVID USHER", "prochains": [], "majeurs": []},
    {"nom": "DAWEN", "prochains": [], "majeurs": []},
    {"nom": "DAWN", "prochains": [], "majeurs": []},
    {"nom": "DAYA", "prochains": [], "majeurs": []},
    {"nom": "DEAD OR ALIVE", "prochains": [], "majeurs": []},
    {"nom": "DEAN LEWIS", "prochains": [], "majeurs": []},
    {"nom": "DEBARGE", "prochains": [], "majeurs": []},
    {"nom": "DEEE-LITE", "prochains": [], "majeurs": []},
    {"nom": "DEF LEPPARD", "prochains": [], "majeurs": []},
    {"nom": "DEFAULT", "prochains": [], "majeurs": []},
    {"nom": "DEMI LOVATO", "prochains": [], "majeurs": []},
    {"nom": "DENIECE WILLIAMS", "prochains": [], "majeurs": []},
    {"nom": "DEPECHE MODE", "prochains": [], "majeurs": []},
    {"nom": "DERMOT KENNEDY", "prochains": [], "majeurs": []},
    {"nom": "DES'REE", "prochains": [], "majeurs": []},
    {"nom": "DESTINY'S CHILD", "prochains": [], "majeurs": []},
    {"nom": "DEXY'S MIDNIGHT RUNNERS", "prochains": [], "majeurs": []},
    {"nom": "DIANA KING", "prochains": [], "majeurs": []},
    {"nom": "DIANA ROSS", "prochains": [], "majeurs": []},
    {"nom": "DIDO", "prochains": [], "majeurs": []},
    {"nom": "DIERKS BENTLEY", "prochains": [], "majeurs": []},
    {"nom": "DILLON FRANCIS", "prochains": [], "majeurs": []},
    {"nom": "DIONNE WARWICK", "prochains": [], "majeurs": []},
    {"nom": "DIRE STRAITS", "prochains": [], "majeurs": []},
    {"nom": "DISCLOSURE", "prochains": [], "majeurs": []},
    {"nom": "DJ CASSIDY", "prochains": [], "majeurs": []},
    {"nom": "DJ JAZZY JEFF", "prochains": [], "majeurs": []},
    {"nom": "DJ KHALED", "prochains": [], "majeurs": []},
    {"nom": "DJ SAMMY", "prochains": [], "majeurs": []},
    {"nom": "DJ SNAKE", "prochains": [], "majeurs": []},
    {"nom": "DNCE", "prochains": [], "majeurs": []},
    {"nom": "DOJA CAT", "prochains": [], "majeurs": []},
    {"nom": "DOLLY PARTON", "prochains": [], "majeurs": []},
    {"nom": "DOMBRESKY", "prochains": [], "majeurs": []},
    {"nom": "DON HENLEY", "prochains": [], "majeurs": []},
    {"nom": "DON MCLEAN", "prochains": [], "majeurs": []},
    {"nom": "DONNA SUMMER", "prochains": [], "majeurs": []},
    {"nom": "DOOBIE BROTHERS", "prochains": [], "majeurs": []},
    {"nom": "DR. ALBAN", "prochains": [], "majeurs": []},
    {"nom": "DR. DRE", "prochains": [], "majeurs": []},
    {"nom": "DRAKE", "prochains": [], "majeurs": []},
    {"nom": "DUA LIPA", "prochains": [], "majeurs": [{"date": "15-16 mai", "salle": "Centre Bell"}]},
    {"nom": "DUCK SAUCE", "prochains": [], "majeurs": []},
    {"nom": "DUNCAN LAURENCE", "prochains": [], "majeurs": []},
    {"nom": "DURAN DURAN", "prochains": [], "majeurs": []},
    {"nom": "EAGLE-EYE CHERRY", "prochains": [], "majeurs": []},
    {"nom": "EAGLES", "prochains": [], "majeurs": []},
    {"nom": "EARTH, WIND & FIRE", "prochains": [], "majeurs": []},
    {"nom": "ED SHEERAN", "prochains": [], "majeurs": []},
    {"nom": "EDDIE MURPHY", "prochains": [], "majeurs": []},
    {"nom": "EDWARD SHARPE", "prochains": [], "majeurs": []},
    {"nom": "EDWIN", "prochains": [], "majeurs": []},
    {"nom": "EIFFEL 65", "prochains": [], "majeurs": []},
    {"nom": "ELECTRIC LIGHT ORCHESTRA", "prochains": [], "majeurs": []},
    {"nom": "ELIJAH WOODS", "prochains": [], "majeurs": []},
    {"nom": "ELIZA ROSE", "prochains": [], "majeurs": []},
    {"nom": "ELLA HENDERSON", "prochains": [], "majeurs": []},
    {"nom": "ELLE KING", "prochains": [], "majeurs": []},
    {"nom": "ELLIE GOULDING", "prochains": [], "majeurs": []},
    {"nom": "ELTON JOHN", "prochains": [], "majeurs": []},
    {"nom": "ELVIS PRESLEY", "prochains": [], "majeurs": []},
    {"nom": "EMF", "prochains": [], "majeurs": []},
    {"nom": "EMILE BILODEAU", "prochains": [{"date": "5 juin 20h", "salle": "Club Dix 30"}], "majeurs": []},
    {"nom": "EMINEM", "prochains": [], "majeurs": []},
    {"nom": "EMOTIONS", "prochains": [], "majeurs": []},
    {"nom": "EN VOGUE", "prochains": [], "majeurs": []},
    {"nom": "ENIGMA", "prochains": [], "majeurs": []},
    {"nom": "ENRIQUE IGLESIAS", "prochains": [], "majeurs": []},
    {"nom": "ENYA", "prochains": [], "majeurs": []},
    {"nom": "ERIC LAPOINTE", "prochains": [{"date": "2 mai 19h30", "salle": "Club Dix 30"}], "majeurs": []},
    {"nom": "ERIC PRYDZ", "prochains": [], "majeurs": []},
    {"nom": "EROS RAMAZZOTTI", "prochains": [], "majeurs": []},
    {"nom": "ERUPTION", "prochains": [], "majeurs": []},
    {"nom": "EUROPE", "prochains": [], "majeurs": []},
    {"nom": "EURYTHMICS", "prochains": [], "majeurs": []},
    {"nom": "EVANESCENCE", "prochains": [], "majeurs": []},
    {"nom": "EVE", "prochains": [], "majeurs": []},
    {"nom": "EVERYTHING BUT THE GIRL", "prochains": [], "majeurs": []},
    {"nom": "EXTREME", "prochains": [], "majeurs": []},
    {"nom": "FAITH HILL", "prochains": [], "majeurs": []},
    {"nom": "FALCO", "prochains": [], "majeurs": []},
    {"nom": "FALL OUT BOY", "prochains": [], "majeurs": []},
    {"nom": "FAMILY OF THE YEAR", "prochains": [], "majeurs": []},
    {"nom": "FASTBALL", "prochains": [], "majeurs": []},
    {"nom": "FATBOY SLIM", "prochains": [], "majeurs": []},
    {"nom": "FELIX JAEHN", "prochains": [], "majeurs": []},
    {"nom": "FERGIE", "prochains": [], "majeurs": []},
    {"nom": "FETTY WAP", "prochains": [], "majeurs": []},
    {"nom": "FIFTH HARMONY", "prochains": [], "majeurs": []},
    {"nom": "FILTER", "prochains": [], "majeurs": []},
    {"nom": "FINE YOUNG CANNIBALS", "prochains": [], "majeurs": []},
    {"nom": "FIREHOUSE", "prochains": [], "majeurs": []},
    {"nom": "FITZ AND THE TANTRUMS", "prochains": [], "majeurs": []},
    {"nom": "FIVE FOR FIGHTING", "prochains": [], "majeurs": []},
    {"nom": "FLEETWOOD MAC", "prochains": [], "majeurs": []},
    {"nom": "FLIGHT FACILITIES", "prochains": [], "majeurs": []},
    {"nom": "FLO RIDA", "prochains": [], "majeurs": []},
    {"nom": "FLORENCE AND THE MACHINE", "prochains": [], "majeurs": []},
    {"nom": "FLORIDA GEORGIA LINE", "prochains": [], "majeurs": []},
    {"nom": "FOO FIGHTERS", "prochains": [], "majeurs": []},
    {"nom": "FOREIGNER", "prochains": [], "majeurs": []},
    {"nom": "FOSTER THE PEOPLE", "prochains": [], "majeurs": []},
    {"nom": "FOUNTAINS OF WAYNE", "prochains": [], "majeurs": []},
    {"nom": "FRANCIS DEGRANDPRE", "prochains": [{"date": "1er octobre 20h", "salle": "Théâtre Beanfield"}], "majeurs": []},
    {"nom": "FRANK SINATRA", "prochains": [], "majeurs": []},
    {"nom": "FRANKIE GOES TO HOLLYWOOD", "prochains": [], "majeurs": []},
    {"nom": "FREDZ", "prochains": [], "majeurs": [{"date": "29 et 30 mai 20h", "salle": "MTelus"}]},
    {"nom": "FUN", "prochains": [], "majeurs": []},
    {"nom": "GAB BOUCHARD", "prochains": [], "majeurs": [{"date": "24 avril 20h", "salle": "MTelus"}]},
    {"nom": "GABRIELLA", "prochains": [], "majeurs": []},
    {"nom": "GABRIELLE", "prochains": [], "majeurs": []},
    {"nom": "GALA", "prochains": [], "majeurs": []},
    {"nom": "GAROU", "prochains": [{"date": "12 avril 19h00", "salle": "Théâtre Manuevie Brossard"}], "majeurs": []},
    {"nom": "GARTH BROOKS", "prochains": [], "majeurs": []},
    {"nom": "GENESIS", "prochains": [], "majeurs": []},
    {"nom": "GEORGE EZRA", "prochains": [], "majeurs": []},
    {"nom": "GEORGE HARRISON", "prochains": [], "majeurs": []},
    {"nom": "GEORGE MICHAEL", "prochains": [], "majeurs": []},
    {"nom": "GLASS ANIMALS", "prochains": [], "majeurs": []},
    {"nom": "GLENN MEDEIROS", "prochains": [], "majeurs": []},
    {"nom": "GLORIA GAYNOR", "prochains": [], "majeurs": []},
    {"nom": "GNARLS BARKLEY", "prochains": [], "majeurs": []},
    {"nom": "GOO GOO DOLLS", "prochains": [], "majeurs": []},
    {"nom": "GORILLAZ", "prochains": [], "majeurs": [{"date": "3 octobre 19h00", "salle": "Centre Bell"}]},
    {"nom": "GOTYE", "prochains": [], "majeurs": []},
    {"nom": "GREEN DAY", "prochains": [], "majeurs": []},
    {"nom": "GROOVE ARMADA", "prochains": [], "majeurs": []},
    {"nom": "GROUPLOVE", "prochains": [], "majeurs": []},
    {"nom": "GUNS N' ROSES", "prochains": [], "majeurs": []},
    {"nom": "GWEN STEFANI", "prochains": [], "majeurs": []},
    {"nom": "HADDAWAY", "prochains": [], "majeurs": []},
    {"nom": "HAILEE STEINFELD", "prochains": [], "majeurs": []},
    {"nom": "HALL & OATES", "prochains": [], "majeurs": []},
    {"nom": "HARRY STYLES", "prochains": [], "majeurs": []},
    {"nom": "HEART", "prochains": [], "majeurs": []},
    {"nom": "HEDLEY", "prochains": [], "majeurs": []},
    {"nom": "HOOBASTANK", "prochains": [], "majeurs": []},
    {"nom": "HOZIER", "prochains": [], "majeurs": []},
    {"nom": "HUBERT LENOIR", "prochains": [], "majeurs": []},
    {"nom": "HUEY LEWIS AND THE NEWS", "prochains": [], "majeurs": []},
    {"nom": "ICE CUBE", "prochains": [], "majeurs": []},
    {"nom": "ICEHOUSE", "prochains": [], "majeurs": []},
    {"nom": "IGGY AZALEA", "prochains": [], "majeurs": []},
    {"nom": "IGGY POP", "prochains": [], "majeurs": []},
    {"nom": "ILONA MITRECEY", "prochains": [], "majeurs": []},
    {"nom": "IMAGINE DRAGONS", "prochains": [], "majeurs": []},
    {"nom": "INDOCHINE", "prochains": [], "majeurs": []},
    {"nom": "INFORMAYTIONS", "prochains": [], "majeurs": []},
    {"nom": "INI KAMOZE", "prochains": [], "majeurs": []},
    {"nom": "INNER CIRCLE", "prochains": [], "majeurs": []},
    {"nom": "INXS", "prochains": [], "majeurs": []},
    {"nom": "IRENE CARA", "prochains": [], "majeurs": []},
    {"nom": "IRON MAIDEN", "prochains": [], "majeurs": []},
    {"nom": "ISRAEL KAMAKAWIWO'OLE", "prochains": [], "majeurs": []},
    {"nom": "ITZY", "prochains": [], "majeurs": []},
    {"nom": "J. COLE", "prochains": [], "majeurs": []},
    {"nom": "JA RULE", "prochains": [], "majeurs": []},
    {"nom": "JACK JOHNSON", "prochains": [], "majeurs": []},
    {"nom": "JACK WAGNER", "prochains": [], "majeurs": []},
    {"nom": "JAIN", "prochains": [], "majeurs": []},
    {"nom": "JAMES BLUNT", "prochains": [], "majeurs": []},
    {"nom": "JAMES BROWN", "prochains": [], "majeurs": []},
    {"nom": "JAMIROQUAI", "prochains": [], "majeurs": []},
    {"nom": "JANET JACKSON", "prochains": [], "majeurs": []},
    {"nom": "JASON DERULO", "prochains": [], "majeurs": []},
    {"nom": "JASON MRAZ", "prochains": [], "majeurs": []},
    {"nom": "JAY SEAN", "prochains": [], "majeurs": []},
    {"nom": "JAY-Z", "prochains": [], "majeurs": []},
    {"nom": "JEAN-FRANCOIS PAUZE", "prochains": [], "majeurs": [{"date": "4 juin 20h", "salle": "MTelus"}]},
    {"nom": "JENNIFER LOPEZ", "prochains": [], "majeurs": []},
    {"nom": "JENNIFER PAIGE", "prochains": [], "majeurs": []},
    {"nom": "JESSE MCCARTNEY", "prochains": [], "majeurs": []},
    {"nom": "JESSICA SIMPSON", "prochains": [], "majeurs": []},
    {"nom": "JESSIE J", "prochains": [], "majeurs": []},
    {"nom": "JET", "prochains": [], "majeurs": []},
    {"nom": "JEWEL", "prochains": [], "majeurs": []},
    {"nom": "JIMMY CLIFF", "prochains": [], "majeurs": []},
    {"nom": "JIMMY EAT WORLD", "prochains": [], "majeurs": []},
    {"nom": "JOAN JETT", "prochains": [], "majeurs": []},
    {"nom": "JOAN OSBORNE", "prochains": [], "majeurs": []},
    {"nom": "JOE COCKER", "prochains": [], "majeurs": []},
    {"nom": "JOHN COUGAR MELLENCAMP", "prochains": [], "majeurs": []},
    {"nom": "JOHN DENVER", "prochains": [], "majeurs": []},
    {"nom": "JOHN LEGEND", "prochains": [], "majeurs": []},
    {"nom": "JOHN LENNON", "prochains": [], "majeurs": []},
    {"nom": "JOHN MAYER", "prochains": [], "majeurs": []},
    {"nom": "JOHN TRAVOLTA", "prochains": [], "majeurs": []},
    {"nom": "JOHNNY CASH", "prochains": [], "majeurs": []},
    {"nom": "JOHNNY HATES JAZZ", "prochains": [], "majeurs": []},
    {"nom": "JOJO", "prochains": [], "majeurs": []},
    {"nom": "JONAS BROTHERS", "prochains": [], "majeurs": []},
    {"nom": "JOURNEY", "prochains": [], "majeurs": []},
    {"nom": "JOY ENRIQUEZ", "prochains": [], "majeurs": []},
    {"nom": "JUANES", "prochains": [], "majeurs": []},
    {"nom": "JUDAS PRIEST", "prochains": [], "majeurs": []},
    {"nom": "JUICE WRLD", "prochains": [], "majeurs": []},
    {"nom": "JULIET ROBERTS", "prochains": [], "majeurs": []},
    {"nom": "JUNGLE", "prochains": [], "majeurs": []},
    {"nom": "JUSTIN BIEBER", "prochains": [], "majeurs": []},
    {"nom": "JUSTIN TIMBERLAKE", "prochains": [], "majeurs": []},
    {"nom": "K-CI & JOJO", "prochains": [], "majeurs": []},
    {"nom": "K-MARO", "prochains": [], "majeurs": [{"date": "3 octobre 20h", "salle": "Club Soda"}]},
    {"nom": "K.D. LANG", "prochains": [], "majeurs": []},
    {"nom": "KAIN", "prochains": [], "majeurs": []},
    {"nom": "KAISER CHIEFS", "prochains": [], "majeurs": []},
    {"nom": "KANYE WEST", "prochains": [], "majeurs": []},
    {"nom": "KATRINA & THE WAVES", "prochains": [], "majeurs": []},
    {"nom": "KATY PERRY", "prochains": [], "majeurs": []},
    {"nom": "KC & THE SUNSHINE BAND", "prochains": [], "majeurs": []},
    {"nom": "KEANE", "prochains": [], "majeurs": []},
    {"nom": "KELLY CLARKSON", "prochains": [], "majeurs": []},
    {"nom": "KELLY ROWLAND", "prochains": [], "majeurs": []},
    {"nom": "KENNY LOGGINS", "prochains": [], "majeurs": []},
    {"nom": "KENNY ROGERS", "prochains": [], "majeurs": []},
    {"nom": "KESHA", "prochains": [], "majeurs": []},
    {"nom": "KHALID", "prochains": [], "majeurs": []},
    {"nom": "KIDS IN AMERICA", "prochains": [], "majeurs": []},
    {"nom": "KIESZA", "prochains": [], "majeurs": []},
    {"nom": "KIM CARNES", "prochains": [], "majeurs": []},
    {"nom": "KIM WILDE", "prochains": [], "majeurs": []},
    {"nom": "KINGS OF LEON", "prochains": [], "majeurs": []},
    {"nom": "KISS", "prochains": [], "majeurs": []},
    {"nom": "KONGOS", "prochains": [], "majeurs": []},
    {"nom": "KOOL & THE GANG", "prochains": [], "majeurs": []},
    {"nom": "KORN", "prochains": [], "majeurs": []},
    {"nom": "KYLIE MINOGUE", "prochains": [], "majeurs": []},
    {"nom": "LADY GAGA", "prochains": [], "majeurs": []},
    {"nom": "LANA DEL REY", "prochains": [], "majeurs": []},
    {"nom": "LAURA BRANIGAN", "prochains": [], "majeurs": []},
    {"nom": "LAURYN HILL", "prochains": [], "majeurs": []},
    {"nom": "LE CLICK", "prochains": [], "majeurs": []},
    {"nom": "LENNY KRAVITZ", "prochains": [], "majeurs": []},
    {"nom": "LEO SAYER", "prochains": [], "majeurs": []},
    {"nom": "LEON BRIDGES", "prochains": [], "majeurs": []},
    {"nom": "LES TROIS ACCORDS", "prochains": [], "majeurs": [{"date": "8 mai 20h", "salle": "MTelus"}]},
    {"nom": "LEWIS CAPALDI", "prochains": [], "majeurs": [{"date": "21 avril 19h30", "salle": "Centre Bell"}]},
    {"nom": "LIL JON", "prochains": [], "majeurs": []},
    {"nom": "LIL NAS X", "prochains": [], "majeurs": []},
    {"nom": "LIL WAYNE", "prochains": [], "majeurs": []},
    {"nom": "LIMP BIZKIT", "prochains": [], "majeurs": []},
    {"nom": "LINKIN PARK", "prochains": [], "majeurs": []},
    {"nom": "LIONEL RICHIE", "prochains": [], "majeurs": []},
    {"nom": "LIPPS INC.", "prochains": [], "majeurs": []},
    {"nom": "LIQUIDO", "prochains": [], "majeurs": []},
    {"nom": "LISA STANSFIELD", "prochains": [], "majeurs": []},
    {"nom": "LITTLE MIX", "prochains": [], "majeurs": []},
    {"nom": "LITTLE RICHARD", "prochains": [], "majeurs": []},
    {"nom": "LITTLE RIVER BAND", "prochains": [], "majeurs": []},
    {"nom": "LIVE", "prochains": [], "majeurs": []},
    {"nom": "LMFAO", "prochains": [], "majeurs": []},
    {"nom": "LOU ADRIANNE CASSIDY", "prochains": [], "majeurs": [{"date": "12 juin 20h", "salle": "MTelus"}]},
    {"nom": "LOUIS JEAN CORMIER", "prochains": [{"date": "1er avril", "salle": "Club Dix 30"}], "majeurs": []},
    {"nom": "LOU REED", "prochains": [], "majeurs": []},
    {"nom": "LOS DEL RIO", "prochains": [], "majeurs": []},
    {"nom": "LOS LOBOS", "prochains": [], "majeurs": []},
    {"nom": "LOST FREQUENCIES", "prochains": [], "majeurs": []},
    {"nom": "LOU BEGA", "prochains": [], "majeurs": []},
    {"nom": "LOU GRAMM", "prochains": [], "majeurs": []},
    {"nom": "LOVERBOY", "prochains": [], "majeurs": []},
    {"nom": "LUDACRIS", "prochains": [], "majeurs": []},
    {"nom": "LUIS FONSI", "prochains": [], "majeurs": []},
    {"nom": "LUKE COMBS", "info": "Mise en vente vendredi. Denis donnera des billets ce weekend.", "prochains": [], "majeurs": [{"date": "29 et 30 mai 17h30", "salle": "Parc Jean Drapeau"}]},
    {"nom": "LUNCHMONEY LEWIS", "prochains": [], "majeurs": []},
    {"nom": "M.C. HAMMER", "prochains": [], "majeurs": []},
    {"nom": "M.I.A.", "prochains": [], "majeurs": []},
    {"nom": "M2M", "prochains": [], "majeurs": []},
    {"nom": "MAC MILLER", "prochains": [], "majeurs": []},
    {"nom": "MACARENA", "prochains": [], "majeurs": []},
    {"nom": "MACKLEMORE & RYAN LEWIS", "prochains": [], "majeurs": []},
    {"nom": "MACY GRAY", "prochains": [], "majeurs": []},
    {"nom": "MADONNA", "prochains": [], "majeurs": []},
    {"nom": "MAGIC!", "prochains": [], "majeurs": []},
    {"nom": "MAJOR LAZER", "prochains": [], "majeurs": []},
    {"nom": "MARC ANTHONY", "prochains": [], "majeurs": []},
    {"nom": "MARIAH CAREY", "prochains": [], "majeurs": []},
    {"nom": "MARILLION", "prochains": [], "majeurs": []},
    {"nom": "MARIO", "prochains": [], "majeurs": []},
    {"nom": "MAROON 5", "prochains": [], "majeurs": []},
    {"nom": "MARRS", "prochains": [], "majeurs": []},
    {"nom": "MARSHMELLO", "prochains": [], "majeurs": []},
    {"nom": "MARTIKA", "prochains": [], "majeurs": []},
    {"nom": "MARTIN SOLVEIG", "prochains": [], "majeurs": []},
    {"nom": "MARVIN GAYE", "prochains": [], "majeurs": []},
    {"nom": "MARY J. BLIGE", "prochains": [], "majeurs": []},
    {"nom": "MATCHBOX TWENTY", "prochains": [], "majeurs": []},
    {"nom": "MAXI PRIEST", "prochains": [], "majeurs": []},
    {"nom": "MAXIMILIAN HECKER", "prochains": [], "majeurs": []},
    {"nom": "MEAT LOAF", "prochains": [], "majeurs": []},
    {"nom": "MEDUZA", "prochains": [], "majeurs": []},
    {"nom": "MEEK MILL", "prochains": [], "majeurs": []},
    {"nom": "MEGHAN TRAINOR", "prochains": [], "majeurs": []},
    {"nom": "MELANIE C", "prochains": [], "majeurs": []},
    {"nom": "MELANIE MARTINEZ", "prochains": [], "majeurs": []},
    {"nom": "MEN AT WORK", "prochains": [], "majeurs": []},
    {"nom": "MEN WITHOUT HATS", "prochains": [], "majeurs": []},
    {"nom": "METALLICA", "prochains": [], "majeurs": []},
    {"nom": "MGMT", "prochains": [], "majeurs": []},
    {"nom": "MIA MARTINA", "prochains": [], "majeurs": []},
    {"nom": "MIAMI SOUND MACHINE", "prochains": [], "majeurs": []},
    {"nom": "MICA PARIS", "prochains": [], "majeurs": []},
    {"nom": "MICHAEL BUBLE", "prochains": [], "majeurs": []},
    {"nom": "MICHAEL JACKSON", "prochains": [], "majeurs": []},
    {"nom": "MICHEL PAGLIARO", "prochains": [], "majeurs": []},
    {"nom": "MIDNIGHT OIL", "prochains": [], "majeurs": []},
    {"nom": "MIGOS", "prochains": [], "majeurs": []},
    {"nom": "MIKA", "prochains": [], "majeurs": [{"date": "4 mai 20h", "salle": "Place Bell-Laval"}]},
    {"nom": "MIKE POSNER", "prochains": [], "majeurs": []},
    {"nom": "MILEY CYRUS", "prochains": [], "majeurs": []},
    {"nom": "MILLI VANILLI", "prochains": [], "majeurs": []},
    {"nom": "MISSY ELLIOTT", "prochains": [], "majeurs": []},
    {"nom": "MOBY", "prochains": [], "majeurs": []},
    {"nom": "MODERN ENGLISH", "prochains": [], "majeurs": []},
    {"nom": "MODERN TALKING", "prochains": [], "majeurs": []},
    {"nom": "MODJO", "prochains": [], "majeurs": []},
    {"nom": "MONICA", "prochains": [], "majeurs": []},
    {"nom": "MONTELL JORDAN", "prochains": [], "majeurs": []},
    {"nom": "MOTLEY CRUE", "prochains": [], "majeurs": []},
    {"nom": "MR. BIG", "prochains": [], "majeurs": []},
    {"nom": "MR. MISTER", "prochains": [], "majeurs": []},
    {"nom": "MR. PRESIDENT", "prochains": [], "majeurs": []},
    {"nom": "MUSE", "prochains": [], "majeurs": []},
    {"nom": "MY CHEMICAL ROMANCE", "prochains": [], "majeurs": []},
    {"nom": "MYA", "prochains": [], "majeurs": []},
    {"nom": "MYLENE FARMER", "prochains": [], "majeurs": []},
    {"nom": "N*SYNC", "prochains": [], "majeurs": []},
    {"nom": "NATALIE IMBRUGLIA", "prochains": [], "majeurs": []},
    {"nom": "NATASHA BEDINGFIELD", "prochains": [], "majeurs": []},
    {"nom": "NE-YO", "prochains": [], "majeurs": [{"date": "26 juin 20h", "salle": "Centre Bell (avec Akon)"}]},
    {"nom": "NEIL DIAMOND", "prochains": [], "majeurs": []},
    {"nom": "NELLY", "prochains": [], "majeurs": []},
    {"nom": "NELLY FURTADO", "prochains": [], "majeurs": []},
    {"nom": "NENA", "prochains": [], "majeurs": []},
    {"nom": "NENEH CHERRY", "prochains": [], "majeurs": []},
    {"nom": "NEON TREES", "prochains": [], "majeurs": []},
    {"nom": "NEW EDITION", "prochains": [], "majeurs": []},
    {"nom": "NEW KIDS ON THE BLOCK", "prochains": [], "majeurs": []},
    {"nom": "NEW ORDER", "prochains": [], "majeurs": []},
    {"nom": "NEW RADICALS", "prochains": [], "majeurs": []},
    {"nom": "NIALL HORAN", "prochains": [], "majeurs": []},
    {"nom": "NICK JONAS", "prochains": [], "majeurs": []},
    {"nom": "NICKELBACK", "prochains": [], "majeurs": []},
    {"nom": "NICKI MINAJ", "prochains": [], "majeurs": []},
    {"nom": "NIGHTCRAWLERS", "prochains": [], "majeurs": []},
    {"nom": "NINA SIMONE", "prochains": [], "majeurs": []},
    {"nom": "NINE INCH NAILS", "prochains": [], "majeurs": []},
    {"nom": "NIRVANA", "prochains": [], "majeurs": []},
    {"nom": "NO DOUBT", "prochains": [], "majeurs": []},
    {"nom": "NO MERCY", "prochains": [], "majeurs": []},
    {"nom": "NOIR SILENCE", "prochains": [{"date": "18 avril 20h", "salle": "Club Dix 30"}], "majeurs": []},
    {"nom": "NORAH JONES", "prochains": [], "majeurs": []},
    {"nom": "O-TOWN", "prochains": [], "majeurs": []},
    {"nom": "OASIS", "prochains": [], "majeurs": []},
    {"nom": "OLIVIA DEAN", "prochains": [], "majeurs": [{"date": "7 août 20h", "salle": "Centre Bell"}]},
    {"nom": "OLIVIA NEWTON-JOHN", "prochains": [], "majeurs": []},
    {"nom": "OLIVIA RODRIGO", "prochains": [], "majeurs": []},
    {"nom": "OMC", "prochains": [], "majeurs": []},
    {"nom": "OMI", "prochains": [], "majeurs": []},
    {"nom": "ONE DIRECTION", "prochains": [], "majeurs": []},
    {"nom": "ONEREPUBLIC", "prochains": [], "majeurs": []},
    {"nom": "OPUS", "prochains": [], "majeurs": []},
    {"nom": "OTIS REDDING", "prochains": [], "majeurs": []},
    {"nom": "OUTKAST", "prochains": [], "majeurs": []},
    {"nom": "OWL CITY", "prochains": [], "majeurs": []},
    {"nom": "P. DIDDY", "prochains": [], "majeurs": []},
    {"nom": "P!NK", "prochains": [], "majeurs": []},
    {"nom": "PANIC! AT THE DISCO", "prochains": [], "majeurs": []},
    {"nom": "PARAMORE", "prochains": [], "majeurs": []},
    {"nom": "PARIS HILTON", "prochains": [], "majeurs": []},
    {"nom": "PARMALEE", "prochains": [], "majeurs": []},
    {"nom": "PARTYNEXTDOOR", "prochains": [], "majeurs": []},
    {"nom": "PASSENGER", "prochains": [], "majeurs": []},
    {"nom": "PAT BENATAR", "prochains": [], "majeurs": []},
    {"nom": "PAUL MCCARTNEY", "prochains": [], "majeurs": []},
    {"nom": "PAUL SIMON", "prochains": [], "majeurs": []},
    {"nom": "PAUL YOUNG", "prochains": [], "majeurs": []},
    {"nom": "PAULA ABDUL", "prochains": [], "majeurs": []},
    {"nom": "PEARL JAM", "prochains": [], "majeurs": []},
    {"nom": "PEBBLES", "prochains": [], "majeurs": []},
    {"nom": "PET SHOP BOYS", "prochains": [], "majeurs": []},
    {"nom": "PETER GABRIEL", "prochains": [], "majeurs": []},
    {"nom": "PHARRELL WILLIAMS", "prochains": [], "majeurs": []},
    {"nom": "PHIL COLLINS", "prochains": [], "majeurs": []},
    {"nom": "PITBULL", "prochains": [], "majeurs": []},
    {"nom": "PLAIN WHITE T'S", "prochains": [], "majeurs": []},
    {"nom": "POISON", "prochains": [], "majeurs": []},
    {"nom": "POLICE", "prochains": [], "majeurs": []},
    {"nom": "POST MALONE", "prochains": [], "majeurs": []},
    {"nom": "POWELL", "prochains": [], "majeurs": []},
    {"nom": "PRINCE", "prochains": [], "majeurs": []},
    {"nom": "PUDDLE OF MUDD", "prochains": [], "majeurs": []},
    {"nom": "PUFF DADDY", "prochains": [], "majeurs": []},
    {"nom": "QUEEN", "prochains": [], "majeurs": []},
    {"nom": "R.E.M.", "prochains": [], "majeurs": []},
    {"nom": "R.KELLY", "prochains": [], "majeurs": []},
    {"nom": "RADIOHEAD", "prochains": [], "majeurs": []},
    {"nom": "RAY CHARLES", "prochains": [], "majeurs": []},
    {"nom": "RAY PARKER JR.", "prochains": [], "majeurs": []},
    {"nom": "REAL MCCOY", "prochains": [], "majeurs": []},
    {"nom": "RED HOT CHILI PEPPERS", "prochains": [], "majeurs": []},
    {"nom": "REEL 2 REAL", "prochains": [], "majeurs": []},
    {"nom": "REMA", "prochains": [], "majeurs": []},
    {"nom": "REMY ZERO", "prochains": [], "majeurs": []},
    {"nom": "REO SPEEDWAGON", "prochains": [], "majeurs": []},
    {"nom": "REPUBLICA", "prochains": [], "majeurs": []},
    {"nom": "RICHARD MARX", "prochains": [], "majeurs": []},
    {"nom": "RICK ASTLEY", "prochains": [], "majeurs": []},
    {"nom": "RICK JAMES", "prochains": [], "majeurs": []},
    {"nom": "RICKY MARTIN", "prochains": [], "majeurs": []},
    {"nom": "RIHANNA", "prochains": [], "majeurs": []},
    {"nom": "RITA ORA", "prochains": [], "majeurs": []},
    {"nom": "ROBBIE WILLIAMS", "prochains": [], "majeurs": []},
    {"nom": "ROBERT PALMER", "prochains": [], "majeurs": []},
    {"nom": "ROBIN S.", "prochains": [], "majeurs": []},
    {"nom": "ROBIN THICKE", "prochains": [], "majeurs": []},
    {"nom": "ROD STEWART", "prochains": [], "majeurs": []},
    {"nom": "ROLLING STONES", "prochains": [], "majeurs": []},
    {"nom": "ROMEO VOID", "prochains": [], "majeurs": []},
    {"nom": "RONAN KEATING", "prochains": [], "majeurs": []},
    {"nom": "ROSALIA", "prochains": [], "majeurs": []},
    {"nom": "ROXETTE", "prochains": [], "majeurs": []},
    {"nom": "ROY ORBISON", "prochains": [], "majeurs": []},
    {"nom": "RUN D.M.C.", "prochains": [], "majeurs": []},
    {"nom": "RUPAUL", "prochains": [], "majeurs": []},
    {"nom": "S CLUB 7", "prochains": [], "majeurs": []},
    {"nom": "SADE", "prochains": [], "majeurs": []},
    {"nom": "SALT-N-PEPA", "prochains": [], "majeurs": []},
    {"nom": "SAM SMITH", "prochains": [], "majeurs": []},
    {"nom": "SAMANTHA FOX", "prochains": [], "majeurs": []},
    {"nom": "SANTANA", "prochains": [], "majeurs": []},
    {"nom": "SAVAGE GARDEN", "prochains": [], "majeurs": []},
    {"nom": "SCATMAN JOHN", "prochains": [], "majeurs": []},
    {"nom": "SCORPIONS", "prochains": [], "majeurs": []},
    {"nom": "SEAL", "prochains": [], "majeurs": []},
    {"nom": "SEAN KINGSTON", "prochains": [], "majeurs": []},
    {"nom": "SEAN PAUL", "prochains": [], "majeurs": []},
    {"nom": "SELENA GOMEZ", "prochains": [], "majeurs": []},
    {"nom": "SHAGGY", "prochains": [], "majeurs": []},
    {"nom": "SHAKIRA", "prochains": [], "majeurs": []},
    {"nom": "SHANIA TWAIN", "prochains": [], "majeurs": []},
    {"nom": "SHANNON", "prochains": [], "majeurs": []},
    {"nom": "SHAWN MENDES", "prochains": [], "majeurs": []},
    {"nom": "SHERYL CROW", "prochains": [], "majeurs": []},
    {"nom": "SIA", "prochains": [], "majeurs": []},
    {"nom": "SIGALA", "prochains": [], "majeurs": []},
    {"nom": "SILK CITY", "prochains": [], "majeurs": []},
    {"nom": "SIMON & GARFUNKEL", "prochains": [], "majeurs": []},
    {"nom": "SIMPLE MINDS", "prochains": [], "majeurs": []},
    {"nom": "SIMPLE PLAN", "prochains": [], "majeurs": []},
    {"nom": "SIMPLY RED", "prochains": [], "majeurs": []},
    {"nom": "SINEAD O'CONNOR", "prochains": [], "majeurs": []},
    {"nom": "SIR MIX-A-LOT", "prochains": [], "majeurs": []},
    {"nom": "SISTER SLEDGE", "prochains": [], "majeurs": []},
    {"nom": "SIXpence NONE THE RICHER", "prochains": [], "majeurs": []},
    {"nom": "SKRILLEX", "prochains": [], "majeurs": []},
    {"nom": "SMASH MOUTH", "prochains": [], "majeurs": []},
    {"nom": "SMASHING PUMPKINS", "prochains": [], "majeurs": []},
    {"nom": "SNAP!", "prochains": [], "majeurs": []},
    {"nom": "SNOOP DOGG", "prochains": [], "majeurs": []},
    {"nom": "SNOW", "prochains": [], "majeurs": []},
    {"nom": "SNOW PATROL", "prochains": [], "majeurs": []},
    {"nom": "SOFT CELL", "prochains": [], "majeurs": []},
    {"nom": "SONIQUE", "prochains": [], "majeurs": []},
    {"nom": "SONNY & CHER", "prochains": [], "majeurs": []},
    {"nom": "SOPHIE ELLIS-BEXTOR", "prochains": [], "majeurs": []},
    {"nom": "SOUL ASYLUM", "prochains": [], "majeurs": []},
    {"nom": "SOUL II SOUL", "prochains": [], "majeurs": []},
    {"nom": "SOUNDGARDEN", "prochains": [], "majeurs": []},
    {"nom": "SPICE GIRLS", "prochains": [], "majeurs": []},
    {"nom": "SPIN DOCTORS", "prochains": [], "majeurs": []},
    {"nom": "STARDUST", "prochains": [], "majeurs": []},
    {"nom": "STARSHIP", "prochains": [], "majeurs": []},
    {"nom": "STATUS QUO", "prochains": [], "majeurs": []},
    {"nom": "STEELY DAN", "prochains": [], "majeurs": []},
    {"nom": "STEPPENWOLF", "prochains": [], "majeurs": []},
    {"nom": "STEPS", "prochains": [], "majeurs": []},
    {"nom": "STEREOPHONICS", "prochains": [], "majeurs": []},
    {"nom": "STEVE AOKI", "prochains": [], "majeurs": []},
    {"nom": "STEVE MILLER BAND", "prochains": [], "majeurs": []},
    {"nom": "STEVIE B", "prochains": [], "majeurs": []},
    {"nom": "STEVIE WONDER", "prochains": [], "majeurs": []},
    {"nom": "STING", "prochains": [], "majeurs": [{"date": "27 et 29 octobre 20h", "salle": "Théâtre St-Denis"}]},
    {"nom": "STONE TEMPLE PILOTS", "prochains": [], "majeurs": []},
    {"nom": "STRAY CATS", "prochains": [], "majeurs": []},
    {"nom": "STYX", "prochains": [], "majeurs": []},
    {"nom": "SUBLIME", "prochains": [], "majeurs": []},
    {"nom": "SUGAR RAY", "prochains": [], "majeurs": []},
    {"nom": "SUGABABES", "prochains": [], "majeurs": []},
    {"nom": "SUM 41", "prochains": [], "majeurs": []},
    {"nom": "SUPERTRAMP", "prochains": [], "majeurs": []},
    {"nom": "SURVIVOR", "prochains": [], "majeurs": []},
    {"nom": "SUZANNE VEGA", "prochains": [], "majeurs": []},
    {"nom": "SWEDISH HOUSE MAFIA", "prochains": [], "majeurs": []},
    {"nom": "SWEET", "prochains": [], "majeurs": []},
    {"nom": "SYLVESTER", "prochains": [], "majeurs": []},
    {"nom": "SYSTEM OF A DOWN", "prochains": [], "majeurs": []},
    {"nom": "T-PAIN", "prochains": [], "majeurs": []},
    {"nom": "T.I.", "prochains": [], "majeurs": []},
    {"nom": "T.REX", "prochains": [], "majeurs": []},
    {"nom": "TAIO CRUZ", "prochains": [], "majeurs": []},
    {"nom": "TAKE THAT", "prochains": [], "majeurs": []},
    {"nom": "TALKING HEADS", "prochains": [], "majeurs": []},
    {"nom": "TATE MCRAE", "prochains": [], "majeurs": []},
    {"nom": "TAYLOR DAYNE", "prochains": [], "majeurs": []},
    {"nom": "TAYLOR SWIFT", "prochains": [], "majeurs": []},
    {"nom": "TEARS FOR FEARS", "prochains": [], "majeurs": []},
    {"nom": "TECHNOTRONIC", "prochains": [], "majeurs": []},
    {"nom": "TERENCE TRENT D'ARBY", "prochains": [], "majeurs": []},
    {"nom": "THE ANIMALS", "prochains": [], "majeurs": []},
    {"nom": "THE B-52'S", "prochains": [], "majeurs": []},
    {"nom": "THE BEACH BOYS", "prochains": [], "majeurs": []},
    {"nom": "THE BELOVED", "prochains": [], "majeurs": []},
    {"nom": "THE BLACK EYED PEAS", "prochains": [], "majeurs": []},
    {"nom": "THE BOOMTOWN RATS", "prochains": [], "majeurs": []},
    {"nom": "THE BUGGLES", "prochains": [], "majeurs": []},
    {"nom": "THE BYRDS", "prochains": [], "majeurs": []},
    {"nom": "THE CALLING", "prochains": [], "majeurs": []},
    {"nom": "THE CARDIGANS", "prochains": [], "majeurs": []},
    {"nom": "THE CARS", "prochains": [], "majeurs": []},
    {"nom": "THE CHAINSMOKERS", "prochains": [], "majeurs": []},
    {"nom": "THE CHEMICAL BROTHERS", "prochains": [], "majeurs": []},
    {"nom": "THE CLASH", "prochains": [], "majeurs": []},
    {"nom": "THE COMMODORES", "prochains": [], "majeurs": []},
    {"nom": "THE CORRS", "prochains": [], "majeurs": []},
    {"nom": "THE CRANBERRIES", "prochains": [], "majeurs": []},
    {"nom": "THE CURE", "prochains": [], "majeurs": []},
    {"nom": "THE DARKNESS", "prochains": [], "majeurs": []},
    {"nom": "THE DANDY WARHOLS", "prochains": [], "majeurs": []},
    {"nom": "THE DOORS", "prochains": [], "majeurs": []},
    {"nom": "THE FATBACK BAND", "prochains": [], "majeurs": []},
    {"nom": "THE FRAY", "prochains": [], "majeurs": []},
    {"nom": "THE FUGEES", "prochains": [], "majeurs": []},
    {"nom": "THE GAP BAND", "prochains": [], "majeurs": []},
    {"nom": "THE GO-GO'S", "prochains": [], "majeurs": []},
    {"nom": "THE HUMAN LEAGUE", "prochains": [], "majeurs": []},
    {"nom": "THE JACKSON 5", "prochains": [], "majeurs": []},
    {"nom": "THE JAM", "prochains": [], "majeurs": []},
    {"nom": "THE KLF", "prochains": [], "majeurs": []},
    {"nom": "THE KNACK", "prochains": [], "majeurs": []},
    {"nom": "THE KOOKS", "prochains": [], "majeurs": []},
    {"nom": "THE LUMINEERS", "prochains": [], "majeurs": []},
    {"nom": "THE MAMAS & THE PAPAS", "prochains": [], "majeurs": []},
    {"nom": "THE MONKEES", "prochains": [], "majeurs": []},
    {"nom": "THE MOTELS", "prochains": [], "majeurs": []},
    {"nom": "THE OFFSPRING", "prochains": [], "majeurs": []},
    {"nom": "THE OUTFIELD", "prochains": [], "majeurs": []},
    {"nom": "THE POINTER SISTERS", "prochains": [], "majeurs": []},
    {"nom": "THE POLICE", "prochains": [], "majeurs": []},
    {"nom": "THE PRETENDERS", "prochains": [], "majeurs": []},
    {"nom": "THE PROCLAIMERS", "prochains": [], "majeurs": []},
    {"nom": "THE PRODIGY", "prochains": [], "majeurs": []},
    {"nom": "THE PUSSYCAT DOLLS", "prochains": [], "majeurs": []},
    {"nom": "THE RAMONES", "prochains": [], "majeurs": []},
    {"nom": "THE RIGHTEOUS BROTHERS", "prochains": [], "majeurs": []},
    {"nom": "THE ROMANTICS", "prochains": [], "majeurs": []},
    {"nom": "THE SCRIPT", "prochains": [], "majeurs": []},
    {"nom": "THE SHADOWS", "prochains": [], "majeurs": []},
    {"nom": "THE SMITHS", "prochains": [], "majeurs": []},
    {"nom": "THE SOUP DRAGONS", "prochains": [], "majeurs": []},
    {"nom": "THE SPECIALS", "prochains": [], "majeurs": []},
    {"nom": "THE SPINNERS", "prochains": [], "majeurs": []},
    {"nom": "THE STRANGLERS", "prochains": [], "majeurs": []},
    {"nom": "THE STROKES", "prochains": [], "majeurs": []},
    {"nom": "THE STYLE COUNCIL", "prochains": [], "majeurs": []},
    {"nom": "THE SUPREMES", "prochains": [], "majeurs": []},
    {"nom": "THE TEMPTATIONS", "prochains": [], "majeurs": []},
    {"nom": "THE TING TINGS", "prochains": [], "majeurs": []},
    {"nom": "THE TRAMMPS", "prochains": [], "majeurs": []},
    {"nom": "THE TURTLES", "prochains": [], "majeurs": []},
    {"nom": "THE UNDERDOG PROJECT", "prochains": [], "majeurs": []},
    {"nom": "THE VERVE", "prochains": [], "majeurs": []},
    {"nom": "THE WANTED", "prochains": [], "majeurs": []},
    {"nom": "THE WEEKND", "prochains": [], "majeurs": []},
    {"nom": "THE WHO", "prochains": [], "majeurs": []},
    {"nom": "THE ZOMBIES", "prochains": [], "majeurs": []},
    {"nom": "THIERRY HAZARD", "prochains": [], "majeurs": []},
    {"nom": "THIRD EYE BLIND", "prochains": [], "majeurs": []},
    {"nom": "THOMAS DOLBY", "prochains": [], "majeurs": []},
    {"nom": "THOMPSON TWINS", "prochains": [], "majeurs": []},
    {"nom": "THREE DOG NIGHT", "prochains": [], "majeurs": []},
    {"nom": "TIESTO", "prochains": [], "majeurs": []},
    {"nom": "TIMBALAND", "prochains": [], "majeurs": []},
    {"nom": "TINA CHARLES", "prochains": [], "majeurs": []},
    {"nom": "TINA TURNER", "prochains": [], "majeurs": []},
    {"nom": "TLC", "prochains": [], "majeurs": []},
    {"nom": "TOM JONES", "prochains": [], "majeurs": []},
    {"nom": "TOM PETTY", "prochains": [], "majeurs": []},
    {"nom": "TOMMY TUTONE", "prochains": [], "majeurs": []},
    {"nom": "TONE LOC", "prochains": [], "majeurs": []},
    {"nom": "TONI BRAXTON", "prochains": [], "majeurs": []},
    {"nom": "TONY BENNETT", "prochains": [], "majeurs": []},
    {"nom": "TOPLOADER", "prochains": [], "majeurs": []},
    {"nom": "TOTO", "prochains": [], "majeurs": []},
    {"nom": "TOVE LO", "prochains": [], "majeurs": []},
    {"nom": "TRACY CHAPMAN", "prochains": [], "majeurs": []},
    {"nom": "TRAIN", "prochains": [], "majeurs": []},
    {"nom": "TRANSVISION VAMP", "prochains": [], "majeurs": []},
    {"nom": "TRAVIS SCOTT", "prochains": [], "majeurs": []},
    {"nom": "TREY SONGZ", "prochains": [], "majeurs": []},
    {"nom": "TRUE COLORS", "prochains": [], "majeurs": []},
    {"nom": "TWENTY ONE PILOTS", "prochains": [], "majeurs": []},
    {"nom": "TY DOLLA $IGN", "prochains": [], "majeurs": []},
    {"nom": "TYGA", "prochains": [], "majeurs": []},
    {"nom": "TYLA", "prochains": [], "majeurs": []},
    {"nom": "TYLER RICH", "prochains": [], "majeurs": []},
    {"nom": "TYLER SHAW", "prochains": [], "majeurs": []},
    {"nom": "UB40", "prochains": [], "majeurs": [{"date": "19 septembre 20h", "salle": "MTelus"}]},
    {"nom": "ULTRA NATE", "prochains": [], "majeurs": []},
    {"nom": "UNCLE KRACKER", "prochains": [], "majeurs": []},
    {"nom": "USHER", "prochains": [], "majeurs": []},
    {"nom": "USHER F/PITBULL", "prochains": [], "majeurs": []},
    {"nom": "VAAN THIBZ", "prochains": [], "majeurs": []},
    {"nom": "VALERIE CARPENTIER", "prochains": [], "majeurs": []},
    {"nom": "VANCE JOY", "prochains": [], "majeurs": []},
    {"nom": "VANESSA CARLTON", "prochains": [], "majeurs": []},
    {"nom": "VERONIC DICAIRE", "prochains": [], "majeurs": []},
    {"nom": "VILAIN PINGOUIN", "prochains": [], "majeurs": []},
    {"nom": "VINCENT VALLIERES", "prochains": [{"date": "8 avril 20h", "salle": "Théâtre Manuevie Brossard"}, {"date": "16 avril 20h", "salle": "MTelus"}], "majeurs": []},
    {"nom": "WHITNEY HOUSTON", "prochains": [], "majeurs": []},
    {"nom": "WILLIAM CLOUTIER", "prochains": [{"date": "13 mai 20h", "salle": "Club Dix 30"}], "majeurs": []},
    {"nom": "ZAZ", "prochains": [], "majeurs": [{"date": "23 mai 20h", "salle": "Centre Bell"}, {"date": "30 mai", "salle": "Centre Bell"}]}
];
