// =========================================================================
// 🔴 SECTION 1 : CALENDRIER DES PRIORITÉS D'ANTENNE 🔴
// Modifiez les phrases entre les guillemets.
// Le système affichera la bonne journée automatiquement.
// =========================================================================

const prioritesSemaine = {
    "lundi": [
        "Dès 9h: 2h sans interruption + Mega Mix Payants - Jusqu'à 10 000$ à gagner",
        "Gagnez votre voyage au Club Med grâce à Pipi et Cricri",
        "15h55: Ne manquez pas le retour à la maison musicale francophone #1 au pays"
    ],
    "mardi": [
        "Mettez de l'avant l'écoute en ligne - Minimum 1x par show",
        "Le concours de la semaine continue...",
        "Parler de Lady Gaga au Centre Bell"
    ],
    "mercredi": [
        "Grosse annonce à 16h00 !",
        "Tirage : Un voyage à Toronto pour voir Bruno Mars"
    ],
    "jeudi": [
        "C'est le Jeudi Rétro !",
        "N'oubliez pas de plugger le show des Trois Accords"
    ],
    "vendredi": [
        "La compil weekend avec Denis et Gégé: Est-ce que Gone Gone Gone sera toujours #1",
        "VHDW: On débute avec 2h et vos billets pour Gaga",
        "Demain 16h: Il va faire chaud avec Playa Del Party avec MA Berthiaume"
    ],
    "samedi": [
        "La compil weekend avec Denis et Gégé: Est-ce que Gone Gone Gone sera toujours #1",
        "VHDW: On débute avec 2h et vos billets pour Gaga",
        "16h: Il va faire chaud avec Playa Del Party avec MA Berthiaume"
    ],
    "dimanche": [
        "Demain 9h: MAINTENANT 2h sans interruption + Mega Mix Payants - Jusqu'à 10 000$ à gagner",
        "Gagnez votre voyage au Club Med grâce à Pipi et Cricri",
        "15h55: Ne manquez pas le retour à la maison musicale francophone #1 au pays"
    ]
};


// =========================================================================
// 🔵 SECTION 2 : BASE DE DONNÉES DES ARTISTES (Pour la recherche) 🔵
// Vous pouvez ajouter des dates ici dans la section "prochains" ou "majeurs"
// Format : {"date": "14 Mars 2026", "salle": "Centre Bell"}
// =========================================================================

const baseDeDonnees = [
    {"nom": "'N SYNC", "prochains": [], "majeurs": []},
    {"nom": "24KGOLDN", "prochains": [], "majeurs": []},
    {"nom": "2FRERES", "prochains": [], "majeurs": []},
    {"nom": "ADELE", "prochains": [], "majeurs": []},
    {"nom": "AGUILERA/L.KIM/MYA/PINK", "prochains": [], "majeurs": []},
    {"nom": "ALEX NEVSKY", "prochains": [], "majeurs": []},
    {"nom": "ALEX WARREN", "prochains": [], "majeurs": []},
    {"nom": "ALEXE", "prochains": [], "majeurs": []},
    {"nom": "ALFA ROCOCO", "prochains": [], "majeurs": []},
    {"nom": "ALICIA KEYS", "prochains": [], "majeurs": []},
    {"nom": "ALIOCHA SCHNEIDER", "prochains": [], "majeurs": []},
    {"nom": "ALLIANCE ETHNIK", "prochains": [], "majeurs": []},
    {"nom": "ANASTACIA", "prochains": [], "majeurs": []},
    {"nom": "ANDEE", "prochains": [], "majeurs": []},
    {"nom": "ANDREANNE A. MALETTE", "prochains": [], "majeurs": []},
    {"nom": "ANGELE", "prochains": [], "majeurs": []},
    {"nom": "ANJXLXE", "prochains": [], "majeurs": []},
    {"nom": "ARIANA GRANDE", "prochains": [], "majeurs": []},
    {"nom": "ARIANE BRUNET", "prochains": [], "majeurs": []},
    {"nom": "ARIANE MOFFATT", "prochains": [], "majeurs": []},
    {"nom": "ASWELL", "prochains": [], "majeurs": []},
    {"nom": "BACKSTREET BOYS", "prochains": [], "majeurs": []},
    {"nom": "BAD BUNNY", "prochains": [], "majeurs": []},
    {"nom": "BBNO$", "prochains": [], "majeurs": []},
    {"nom": "BEN L'ONCLE SOUL", "prochains": [], "majeurs": []},
    {"nom": "BENSON BOONE", "prochains": [], "majeurs": []},
    {"nom": "BEYONCE", "prochains": [], "majeurs": []},
    {"nom": "BIGFLO & OLI", "prochains": [], "majeurs": []},
    {"nom": "BILLIE EILISH", "prochains": [], "majeurs": []},
    {"nom": "BLACK EYED PEAS", "prochains": [], "majeurs": []},
    {"nom": "BLACK EYED PEAS/OZUNA/J.REY", "prochains": [], "majeurs": []},
    {"nom": "BLEU JEANS BLEU", "prochains": [], "majeurs": []},
    {"nom": "BLU CANTRELL", "prochains": [], "majeurs": []},
    {"nom": "BOB MARLEY & THE WAILERS", "prochains": [], "majeurs": []},
    {"nom": "BOB SINCLAR & KIESZA", "prochains": [], "majeurs": []},
    {"nom": "BON JOVI", "prochains": [], "majeurs": []},
    {"nom": "BRANDY W/MONICA", "prochains": [], "majeurs": []},
    {"nom": "BRITNEY SPEARS", "prochains": [], "majeurs": []},
    {"nom": "BRUNO MARS", "prochains": [], "majeurs": [{"date": "23 au 30 Mai 2026", "salle": "Rogers Stadium, Toronto"}]},
    {"nom": "BRYAN ADAMS", "prochains": [], "majeurs": []},
    {"nom": "CALVIN HARRIS", "prochains": [], "majeurs": []},
    {"nom": "CAMILA CABELLO", "prochains": [], "majeurs": []},
    {"nom": "CARLY RAE JEPSEN", "prochains": [], "majeurs": []},
    {"nom": "CELINE DION", "prochains": [], "majeurs": []},
    {"nom": "CHAPPELL ROAN", "prochains": [], "majeurs": []},
    {"nom": "CHARLIE PUTH", "prochains": [], "majeurs": []},
    {"nom": "CHARLIE-ROSE", "prochains": [], "majeurs": []},
    {"nom": "CHARLOTTE CARDIN", "prochains": [{"date": "23 Avril 2026", "salle": "Rennes, France"}, {"date": "24 Avril 2026", "salle": "Arkéa Arena, Floirac"}], "majeurs": []},
    {"nom": "CHRISTINA AGUILERA", "prochains": [], "majeurs": []},
    {"nom": "CLASSE MOYENNE & RYMZ", "prochains": [], "majeurs": []},
    {"nom": "CLAUDE BEGIN", "prochains": [], "majeurs": []},
    {"nom": "CLAY AND FRIENDS", "prochains": [], "majeurs": []},
    {"nom": "CLEAN BANDIT & ANNE-MARIE", "prochains": [], "majeurs": []},
    {"nom": "CLEMENT JACQUES", "prochains": [], "majeurs": []},
    {"nom": "CLODELLE", "prochains": [], "majeurs": []},
    {"nom": "COEUR DE PIRATE", "prochains": [], "majeurs": []},
    {"nom": "COLBIE CAILLAT", "prochains": [], "majeurs": []},
    {"nom": "COLDPLAY", "prochains": [], "majeurs": []},
    {"nom": "COMMENT DEBORD", "prochains": [], "majeurs": []},
    {"nom": "COOLIO", "prochains": [], "majeurs": []},
    {"nom": "CORNEILLE", "prochains": [], "majeurs": []},
    {"nom": "CRIS CAB", "prochains": [], "majeurs": []},
    {"nom": "CYRIL", "prochains": [], "majeurs": []},
    {"nom": "D GUETTA, T SWIMS, TONES AND I", "prochains": [], "majeurs": []},
    {"nom": "DAFT PUNK", "prochains": [], "majeurs": []},
    {"nom": "DAMIEN LAURETTA", "prochains": [], "majeurs": []},
    {"nom": "DANIEL BELANGER", "prochains": [], "majeurs": []},
    {"nom": "DASHA", "prochains": [], "majeurs": []},
    {"nom": "DAVID GUETTA", "prochains": [], "majeurs": []},
    {"nom": "DESTINY'S CHILD", "prochains": [], "majeurs": []},
    {"nom": "DIDO", "prochains": [], "majeurs": []},
    {"nom": "DOBACARACOL", "prochains": [], "majeurs": []},
    {"nom": "DOMENO", "prochains": [], "majeurs": []},
    {"nom": "DON JUAN", "prochains": [], "majeurs": []},
    {"nom": "DRAKE", "prochains": [], "majeurs": []},
    {"nom": "DRAKE F/MAJID JORDAN", "prochains": [], "majeurs": []},
    {"nom": "DUA LIPA", "prochains": [], "majeurs": []},
    {"nom": "DUBMATIQUE", "prochains": [], "majeurs": []},
    {"nom": "DUMAS", "prochains": [], "majeurs": []},
    {"nom": "DY", "prochains": [], "majeurs": []},
    {"nom": "ED SHEERAN", "prochains": [], "majeurs": [{"date": "20-21-22 Août 2026", "salle": "Rogers Centre, Toronto"}]},
    {"nom": "ELI ET PAPILLON", "prochains": [], "majeurs": []},
    {"nom": "ELI ROSE", "prochains": [], "majeurs": []},
    {"nom": "ELIJAH WOODS X JAMIE FINE", "prochains": [], "majeurs": []},
    {"nom": "ELLA LANGLEY", "prochains": [], "majeurs": []},
    {"nom": "ELTON JOHN & DUA LIPA", "prochains": [], "majeurs": []},
    {"nom": "EMILE BILODEAU", "prochains": [], "majeurs": []},
    {"nom": "EMINEM", "prochains": [], "majeurs": []},
    {"nom": "EMMANUELLE QUERRY", "prochains": [], "majeurs": []},
    {"nom": "ENRIQUE IGLESIAS", "prochains": [], "majeurs": []},
    {"nom": "ESTELLE", "prochains": [], "majeurs": []},
    {"nom": "EVANESCENCE", "prochains": [], "majeurs": []},
    {"nom": "FANNY BLOOM", "prochains": [], "majeurs": []},
    {"nom": "FERGIE", "prochains": [], "majeurs": []},
    {"nom": "FINAL STATE", "prochains": [], "majeurs": []},
    {"nom": "FOUKI", "prochains": [{"date": "13 Juillet 2026", "salle": "FEQ (Plaines d'Abraham)"}, {"date": "14 Novembre 2026", "salle": "Place Bell, Laval"}], "majeurs": []},
    {"nom": "FRANCE D'AMOUR", "prochains": [], "majeurs": []},
    {"nom": "FRANK WALKER", "prochains": [], "majeurs": []},
    {"nom": "FREDZ", "prochains": [], "majeurs": []},
    {"nom": "FUGEES", "prochains": [], "majeurs": []},
    {"nom": "FUSO", "prochains": [], "majeurs": []},
    {"nom": "GABBY BARRETT", "prochains": [], "majeurs": []},
    {"nom": "GABRIEL FREDETTE", "prochains": [], "majeurs": []},
    {"nom": "GABRIELLE DESTROISMAISONS", "prochains": [], "majeurs": []},
    {"nom": "GNARLS BARKLEY", "prochains": [], "majeurs": []},
    {"nom": "GOO GOO DOLLS", "prochains": [], "majeurs": []},
    {"nom": "GOTYE", "prochains": [], "majeurs": []},
    {"nom": "GRACIE ABRAMS", "prochains": [], "majeurs": []},
    {"nom": "GREEN DAY", "prochains": [], "majeurs": []},
    {"nom": "HARRY STYLES", "prochains": [], "majeurs": []},
    {"nom": "HUBERT LENOIR", "prochains": [], "majeurs": []},
    {"nom": "HUNTR/X, EJAE, AUDREY NUNA...", "prochains": [], "majeurs": []},
    {"nom": "INDOCHINE", "prochains": [], "majeurs": []},
    {"nom": "INFINI-T", "prochains": [], "majeurs": []},
    {"nom": "J BALVIN F/WILLY WILLIAM", "prochains": [], "majeurs": []},
    {"nom": "JACK JOHNSON", "prochains": [], "majeurs": []},
    {"nom": "JAIN", "prochains": [], "majeurs": []},
    {"nom": "JAMES BLUNT", "prochains": [], "majeurs": []},
    {"nom": "JANET", "prochains": [], "majeurs": []},
    {"nom": "JASON DERULO", "prochains": [], "majeurs": []},
    {"nom": "JASON DERULO & MICHAEL BUBLE", "prochains": [], "majeurs": []},
    {"nom": "JASON DERULO X NUKA", "prochains": [], "majeurs": []},
    {"nom": "JAWSH 685 X JASON DERULO X BTS", "prochains": [], "majeurs": []},
    {"nom": "JAX JONES", "prochains": [], "majeurs": []},
    {"nom": "JAY SCOTT", "prochains": [], "majeurs": []},
    {"nom": "JAY TREPANIER", "prochains": [], "majeurs": []},
    {"nom": "JEAN LELOUP", "prochains": [], "majeurs": []},
    {"nom": "JENNIFER LOPEZ", "prochains": [], "majeurs": []},
    {"nom": "JENNIFER LOPEZ & DAVID GUETTA", "prochains": [], "majeurs": []},
    {"nom": "JENNIFER LOPEZ F/PITBULL", "prochains": [], "majeurs": []},
    {"nom": "JENNIFER PAIGE", "prochains": [], "majeurs": []},
    {"nom": "JEROME COUTURE", "prochains": [], "majeurs": []},
    {"nom": "JESSIE J", "prochains": [], "majeurs": []},
    {"nom": "JF PAUZE", "prochains": [], "majeurs": []},
    {"nom": "JODIE RESTHER", "prochains": [], "majeurs": []},
    {"nom": "JOHN LEGEND", "prochains": [], "majeurs": []},
    {"nom": "JONAS & THE MASSIVE ATTRACTION", "prochains": [], "majeurs": []},
    {"nom": "JONAS BROTHERS", "prochains": [], "majeurs": []},
    {"nom": "JONATHAN PAINCHAUD", "prochains": [], "majeurs": []},
    {"nom": "JONATHAN ROY", "prochains": [], "majeurs": []},
    {"nom": "JUSTIN BIEBER", "prochains": [], "majeurs": []},
    {"nom": "JUSTIN TIMBERLAKE", "prochains": [], "majeurs": []},
    {"nom": "K-MARO", "prochains": [], "majeurs": []},
    {"nom": "K.O.D.", "prochains": [], "majeurs": []},
    {"nom": "KAIN", "prochains": [], "majeurs": []},
    {"nom": "KANE BROWN", "prochains": [], "majeurs": []},
    {"nom": "KANE BROWN & MARSHMELLO", "prochains": [], "majeurs": []},
    {"nom": "KATE RYAN", "prochains": [], "majeurs": []},
    {"nom": "KATO", "prochains": [], "majeurs": []},
    {"nom": "KATSEYE", "prochains": [], "majeurs": []},
    {"nom": "KATY PERRY", "prochains": [], "majeurs": []},
    {"nom": "KAYLEM", "prochains": [], "majeurs": []},
    {"nom": "KE$HA", "prochains": [], "majeurs": []},
    {"nom": "KELLY CLARKSON", "prochains": [], "majeurs": []},
    {"nom": "KHALED", "prochains": [], "majeurs": []},
    {"nom": "KING MELROSE", "prochains": [], "majeurs": []},
    {"nom": "KORIASS", "prochains": [], "majeurs": []},
    {"nom": "KUNGS VS COOKIN' ON 3 BURNERS", "prochains": [], "majeurs": []},
    {"nom": "KYGO & DONNA SUMMER", "prochains": [], "majeurs": []},
    {"nom": "KYGO & WHITNEY HOUSTON", "prochains": [], "majeurs": []},
    {"nom": "KYLIE MINOGUE", "prochains": [], "majeurs": []},
    {"nom": "LADY GAGA", "prochains": [{"date": "02 Avril 2026", "salle": "Centre Bell, Montréal"}, {"date": "03 Avril 2026", "salle": "Centre Bell, Montréal"}, {"date": "06 Avril 2026", "salle": "Centre Bell, Montréal"}], "majeurs": []},
    {"nom": "LARA FABIAN", "prochains": [], "majeurs": []},
    {"nom": "LATTO", "prochains": [], "majeurs": []},
    {"nom": "LAURENCE NERBONNE", "prochains": [], "majeurs": []},
    {"nom": "LAURIE", "prochains": [], "majeurs": []},
    {"nom": "LEANN RIMES", "prochains": [], "majeurs": []},
    {"nom": "LEONA LEWIS", "prochains": [], "majeurs": []},
    {"nom": "LES COLOCS", "prochains": [], "majeurs": []},
    {"nom": "LES COWBOYS FRINGANTS", "prochains": [], "majeurs": []},
    {"nom": "LES FRERES A CH'VAL", "prochains": [], "majeurs": []},
    {"nom": "LES TROIS ACCORDS", "prochains": [{"date": "17 Avril 2026", "salle": "Impérial Bell, Québec"}, {"date": "08 Mai 2026", "salle": "MTELUS, Montréal"}], "majeurs": [{"date": "17 Avril 2027", "salle": "Centre Vidéotron, Québec"}]},
    {"nom": "LEWIS CAPALDI", "prochains": [{"date": "21 Avril 2026", "salle": "Centre Bell, Montréal"}], "majeurs": []},
    {"nom": "LGS", "prochains": [], "majeurs": []},
    {"nom": "LIZZO", "prochains": [], "majeurs": []},
    {"nom": "LOLA YOUNG", "prochains": [], "majeurs": []},
    {"nom": "LOU-ADRIANE CASSIDY", "prochains": [], "majeurs": []},
    {"nom": "LOUD", "prochains": [], "majeurs": []},
    {"nom": "LOUIS-JEAN CORMIER", "prochains": [], "majeurs": []},
    {"nom": "LOVA", "prochains": [], "majeurs": []},
    {"nom": "LUDOVICK BOURGEOIS", "prochains": [], "majeurs": []},
    {"nom": "LUIS FONSI & DADDY YANKEE", "prochains": [], "majeurs": []},
    {"nom": "LUIS FONSI & DEMI LOVATO", "prochains": [], "majeurs": []},
    {"nom": "LUKE COMBS", "prochains": [], "majeurs": []},
    {"nom": "MACKLEMORE & RYAN LEWIS", "prochains": [], "majeurs": []},
    {"nom": "MADCON", "prochains": [], "majeurs": []},
    {"nom": "MADIBA KING", "prochains": [], "majeurs": []},
    {"nom": "MADONNA", "prochains": [], "majeurs": []},
    {"nom": "MAGIC!", "prochains": [], "majeurs": []},
    {"nom": "MAJOR LAZER", "prochains": [], "majeurs": []},
    {"nom": "MALUMA", "prochains": [], "majeurs": []},
    {"nom": "MANAU", "prochains": [], "majeurs": []},
    {"nom": "MARC DUPRE", "prochains": [], "majeurs": []},
    {"nom": "MARCO EMA", "prochains": [], "majeurs": []},
    {"nom": "MARIE-LUCE BELAND", "prochains": [], "majeurs": []},
    {"nom": "MARIE-MAI", "prochains": [], "majeurs": []},
    {"nom": "MARIE-PIERRE ARTHUR", "prochains": [], "majeurs": []},
    {"nom": "MARIEME, CLODELLE & IMPOSS", "prochains": [], "majeurs": []},
    {"nom": "MARK AMBOR", "prochains": [], "majeurs": []},
    {"nom": "MARK MORRISON", "prochains": [], "majeurs": []},
    {"nom": "MARK RONSON", "prochains": [], "majeurs": []},
    {"nom": "MAROON 5", "prochains": [], "majeurs": []},
    {"nom": "MARSHMELLO & FARRUKO", "prochains": [], "majeurs": []},
    {"nom": "MARSHMELLO & MANUEL TURIZO", "prochains": [], "majeurs": []},
    {"nom": "MARY J. BLIGE", "prochains": [], "majeurs": []},
    {"nom": "MATT LANG", "prochains": [], "majeurs": []},
    {"nom": "MATT SIMONS", "prochains": [], "majeurs": []},
    {"nom": "MAX MCNOWN", "prochains": [], "majeurs": []},
    {"nom": "MAYFLY", "prochains": [], "majeurs": []},
    {"nom": "MEGHAN TRAINOR", "prochains": [], "majeurs": []},
    {"nom": "MELISANE", "prochains": [], "majeurs": []},
    {"nom": "MEN AT WORK", "prochains": [], "majeurs": []},
    {"nom": "MEN WITHOUT HATS", "prochains": [], "majeurs": []},
    {"nom": "MICHAEL JACKSON", "prochains": [], "majeurs": []},
    {"nom": "MIKA", "prochains": [{"date": "04 Mai 2026", "salle": "Place Bell, Laval"}], "majeurs": []},
    {"nom": "MIKE CLAY", "prochains": [], "majeurs": []},
    {"nom": "MIKE DEMERO & ALOE BLACC", "prochains": [], "majeurs": []},
    {"nom": "MIKE DEMERO & DYNORO", "prochains": [], "majeurs": []},
    {"nom": "MIKE DEMERO & ZAGATA", "prochains": [], "majeurs": []},
    {"nom": "MILEY CYRUS", "prochains": [], "majeurs": []},
    {"nom": "MILKY CHANCE", "prochains": [], "majeurs": []},
    {"nom": "MILOW", "prochains": [], "majeurs": []},
    {"nom": "MISTEUR VALAIRE/KARIM OUELLET", "prochains": [], "majeurs": []},
    {"nom": "MOHOMBI", "prochains": [], "majeurs": []},
    {"nom": "MR. BIG", "prochains": [], "majeurs": []},
    {"nom": "MYLES SMITH", "prochains": [], "majeurs": []},
    {"nom": "MYLES SMITH & NIALL HORAN", "prochains": [], "majeurs": []},
    {"nom": "NATALIE IMBRUGLIA", "prochains": [], "majeurs": []},
    {"nom": "NATASHA BEDINGFIELD", "prochains": [], "majeurs": []},
    {"nom": "NE-YO", "prochains": [], "majeurs": []},
    {"nom": "NELLY", "prochains": [], "majeurs": []},
    {"nom": "NELLY FURTADO", "prochains": [], "majeurs": []},
    {"nom": "NICKY YOURE", "prochains": [], "majeurs": []},
    {"nom": "NINA SKY", "prochains": [], "majeurs": []},
    {"nom": "NO DOUBT", "prochains": [], "majeurs": []},
    {"nom": "NOAH KAHAN", "prochains": [], "majeurs": []},
    {"nom": "OASIS", "prochains": [], "majeurs": []},
    {"nom": "OFENBACH", "prochains": [], "majeurs": []},
    {"nom": "OKOUME", "prochains": [], "majeurs": []},
    {"nom": "OLIVIA DEAN", "prochains": [], "majeurs": []},
    {"nom": "OLIVIA RODRIGO", "prochains": [], "majeurs": []},
    {"nom": "OLIVIER DION", "prochains": [], "majeurs": []},
    {"nom": "OMI", "prochains": [], "majeurs": []},
    {"nom": "ONE DIRECTION", "prochains": [], "majeurs": []},
    {"nom": "ONEREPUBLIC", "prochains": [], "majeurs": []},
    {"nom": "OPUS", "prochains": [], "majeurs": []},
    {"nom": "P!NK", "prochains": [], "majeurs": []},
    {"nom": "PAPI JAY", "prochains": [], "majeurs": []},
    {"nom": "PATRICE MICHAUD", "prochains": [], "majeurs": []},
    {"nom": "PAUL RUSSELL", "prochains": [], "majeurs": []},
    {"nom": "PHARRELL WILLIAMS", "prochains": [], "majeurs": []},
    {"nom": "PHIL COLLINS", "prochains": [], "majeurs": []},
    {"nom": "PIERRE LAPOINTE", "prochains": [], "majeurs": []},
    {"nom": "PITBULL", "prochains": [], "majeurs": []},
    {"nom": "PITBULL F/CHRIS BROWN", "prochains": [], "majeurs": []},
    {"nom": "PLAIN WHITE T'S", "prochains": [], "majeurs": []},
    {"nom": "POST MALONE", "prochains": [], "majeurs": []},
    {"nom": "PRESTON PABLO", "prochains": [], "majeurs": []},
    {"nom": "PRINCE", "prochains": [], "majeurs": []},
    {"nom": "PUSSYCAT DOLLS", "prochains": [], "majeurs": []},
    {"nom": "QUALITE MOTEL", "prochains": [], "majeurs": []},
    {"nom": "QUEEN", "prochains": [], "majeurs": []},
    {"nom": "R. CITY", "prochains": [], "majeurs": []},
    {"nom": "R.E.M.", "prochains": [], "majeurs": []},
    {"nom": "RAU_ZE", "prochains": [], "majeurs": []},
    {"nom": "RAYE", "prochains": [{"date": "12 Avril 2026", "salle": "Place Bell, Laval"}], "majeurs": []},
    {"nom": "RED HOT CHILI PEPPERS", "prochains": [], "majeurs": []},
    {"nom": "REGARD", "prochains": [], "majeurs": []},
    {"nom": "REMA & SELENA GOMEZ", "prochains": [], "majeurs": []},
    {"nom": "REMBRANDTS", "prochains": [], "majeurs": []},
    {"nom": "RICHARD PETIT", "prochains": [], "majeurs": []},
    {"nom": "RICK ASTLEY", "prochains": [], "majeurs": []},
    {"nom": "RICKY MARTIN", "prochains": [], "majeurs": []},
    {"nom": "RIHANNA", "prochains": [], "majeurs": []},
    {"nom": "RITON X NIGHTCRAWLERS", "prochains": [], "majeurs": []},
    {"nom": "ROSALIE AYOTTE", "prochains": [], "majeurs": []},
    {"nom": "ROXANE BRUNEAU", "prochains": [{"date": "18 Mai 2026", "salle": "La Cigale, Paris"}], "majeurs": [{"date": "25 Juin 2026", "salle": "FestiVoix de Trois-Rivières"}]},
    {"nom": "RYAN KENNEDY", "prochains": [], "majeurs": []},
    {"nom": "SABRINA CARPENTER", "prochains": [], "majeurs": []},
    {"nom": "SALEBARBES", "prochains": [], "majeurs": []},
    {"nom": "SAM SMITH", "prochains": [], "majeurs": []},
    {"nom": "SAM SMITH & NORMANI", "prochains": [], "majeurs": []},
    {"nom": "SANTANA", "prochains": [], "majeurs": []},
    {"nom": "SARA DUFOUR", "prochains": [], "majeurs": []},
    {"nom": "SASHA LOPEZ", "prochains": [], "majeurs": []},
    {"nom": "SAVAGE GARDEN", "prochains": [], "majeurs": []},
    {"nom": "SEAN KINGSTON", "prochains": [], "majeurs": []},
    {"nom": "SEAN PAUL", "prochains": [], "majeurs": []},
    {"nom": "SELENA GOMEZ & THE SCENE", "prochains": [], "majeurs": []},
    {"nom": "SHABOOZEY", "prochains": [], "majeurs": []},
    {"nom": "SHABOOZEY & JELLY ROLL", "prochains": [], "majeurs": []},
    {"nom": "SHAGGY", "prochains": [], "majeurs": []},
    {"nom": "SHAKIRA", "prochains": [], "majeurs": []},
    {"nom": "SHAKIRA & ANUEL AA", "prochains": [], "majeurs": []},
    {"nom": "SHAKIRA F/WYCLEF JEAN", "prochains": [], "majeurs": []},
    {"nom": "SHANIA TWAIN", "prochains": [], "majeurs": []},
    {"nom": "SHAWN MENDES", "prochains": [], "majeurs": []},
    {"nom": "SHAWN MENDES & CAMILA CABELLO", "prochains": [], "majeurs": []},
    {"nom": "SHERYL CROW", "prochains": [], "majeurs": []},
    {"nom": "SHY'M", "prochains": [], "majeurs": []},
    {"nom": "SIA", "prochains": [], "majeurs": []},
    {"nom": "SIMPLE PLAN", "prochains": [], "majeurs": []},
    {"nom": "SISTER SLEDGE", "prochains": [], "majeurs": []},
    {"nom": "SKO", "prochains": [], "majeurs": []},
    {"nom": "SOPHIE ELLIS-BEXTOR", "prochains": [], "majeurs": []},
    {"nom": "SPICE GIRLS", "prochains": [], "majeurs": []},
    {"nom": "SPIN DOCTORS", "prochains": [], "majeurs": []},
    {"nom": "STARSHIP", "prochains": [], "majeurs": []},
    {"nom": "STATZZ", "prochains": [], "majeurs": []},
    {"nom": "STROMAE", "prochains": [], "majeurs": []},
    {"nom": "STROMAE F/K WEST/G FORTE", "prochains": [], "majeurs": []},
    {"nom": "TALK", "prochains": [], "majeurs": []},
    {"nom": "TATE MCRAE", "prochains": [], "majeurs": []},
    {"nom": "TAYLOR SWIFT", "prochains": [], "majeurs": []},
    {"nom": "TEDDY SWIMS", "prochains": [], "majeurs": []},
    {"nom": "THE BUGGLES", "prochains": [], "majeurs": []},
    {"nom": "THE OUTFIELD", "prochains": [], "majeurs": []},
    {"nom": "THE POLICE", "prochains": [], "majeurs": []},
    {"nom": "THE TRAMMPS", "prochains": [], "majeurs": []},
    {"nom": "THE WANTED", "prochains": [], "majeurs": []},
    {"nom": "THE WEEKND", "prochains": [], "majeurs": []},
    {"nom": "TIBZ & SYLVAIN DUTHU", "prochains": [], "majeurs": []},
    {"nom": "TIMBALAND", "prochains": [], "majeurs": []},
    {"nom": "TIMBALAND/ONEREPUBLIC", "prochains": [], "majeurs": []},
    {"nom": "TLC", "prochains": [], "majeurs": []},
    {"nom": "TONES AND I", "prochains": [], "majeurs": []},
    {"nom": "TOVE LO", "prochains": [], "majeurs": []},
    {"nom": "TRAIN", "prochains": [], "majeurs": []},
    {"nom": "TRINIX", "prochains": [], "majeurs": []},
    {"nom": "TYLA", "prochains": [], "majeurs": []},
    {"nom": "TYLER RICH", "prochains": [], "majeurs": []},
    {"nom": "TYLER SHAW", "prochains": [], "majeurs": []},
    {"nom": "ULTRA NATE", "prochains": [], "majeurs": []},
    {"nom": "UNCLE KRACKER", "prochains": [], "majeurs": []},
    {"nom": "USHER", "prochains": [], "majeurs": []},
    {"nom": "USHER F/PITBULL", "prochains": [], "majeurs": []},
    {"nom": "VAAN THIBZ", "prochains": [], "majeurs": []},
    {"nom": "VALERIE CARPENTIER", "prochains": [], "majeurs": []},
    {"nom": "VANCE JOY", "prochains": [], "majeurs": []},
    {"nom": "VANESSA CARLTON", "prochains": [], "majeurs": []},
    {"nom": "VERONIC DICAIRE", "prochains": [], "majeurs": []},
    {"nom": "VILAIN PINGOUIN", "prochains": [], "majeurs": []},
    {"nom": "VINCENT VALLIERES", "prochains": [], "majeurs": []},
    {"nom": "WHITNEY HOUSTON", "prochains": [], "majeurs": []},
    {"nom": "WILLIAM CLOUTIER", "prochains": [], "majeurs": []},
    {"nom": "WILLIAM DESLAURIERS", "prochains": [], "majeurs": []},
    {"nom": "WILLY WILLIAM", "prochains": [], "majeurs": []},
    {"nom": "YANNICK", "prochains": [], "majeurs": []},
    {"nom": "ZAGATA", "prochains": [], "majeurs": []},
    {"nom": "ZARA LARSSON", "prochains": [], "majeurs": []},
    {"nom": "ZAZ", "prochains": [{"date": "23 Mai 2026", "salle": "Centre Bell, Montréal"}], "majeurs": []},
    {"nom": "ZEBDA", "prochains": [], "majeurs": []}
];